export interface Product {
  id: number
  name: string
  category: "women" | "men" | "attars" | "testers" | "accessories"
  price: number
  originalPrice?: number
  rating: number
  reviews: number
  image: string
  images?: string[]
  description: string
  notes: {
    top: string[]
    middle: string[]
    base: string[]
  }
  size: string[]
  inStock: boolean
  isNew?: boolean
  isSale?: boolean
  badge?: string
}

export const products: Product[] = [
  {
    id: 1,
    name: "Alsa Fragrance - Midnight Elegance",
    category: "women",
    price: 89.99,
    originalPrice: 109.99,
    rating: 4.8,
    reviews: 124,
    image: "/alsa-midnight-elegance-perfume-bottle.jpg",
    description: "A sophisticated evening fragrance that captures the essence of mystery and allure.",
    notes: {
      top: ["Bergamot", "Black Currant", "Pink Pepper"],
      middle: ["Rose", "Jasmine", "Violet"],
      base: ["Vanilla", "Musk", "Sandalwood"],
    },
    size: ["30ml", "50ml", "100ml"],
    inStock: true,
    isSale: true,
    badge: "Sale",
  },
  {
    id: 2,
    name: "Alsa Fragrance - Royal Oud",
    category: "attars",
    price: 149.99,
    rating: 4.9,
    reviews: 89,
    image: "/alsa-royal-oud-attar-bottle.jpg",
    description: "Premium oud attar crafted from the finest agarwood, embodying luxury and tradition.",
    notes: {
      top: ["Saffron", "Rose"],
      middle: ["Oud", "Amber"],
      base: ["Musk", "Sandalwood", "Patchouli"],
    },
    size: ["6ml", "12ml"],
    inStock: true,
    isNew: true,
    badge: "Premium",
  },
  {
    id: 3,
    name: "Alsa Fragrance - Urban Legend",
    category: "men",
    price: 79.99,
    rating: 4.7,
    reviews: 156,
    image: "/alsa-urban-legend-cologne-bottle.jpg",
    description: "A modern masculine fragrance for the contemporary urban gentleman.",
    notes: {
      top: ["Lemon", "Grapefruit", "Mint"],
      middle: ["Lavender", "Geranium", "Cardamom"],
      base: ["Cedarwood", "Vetiver", "Ambergris"],
    },
    size: ["50ml", "100ml"],
    inStock: true,
  },
  {
    id: 4,
    name: "Alsa Fragrance - Rose Garden",
    category: "women",
    price: 94.99,
    rating: 4.8,
    reviews: 203,
    image: "/alsa-rose-garden-perfume-bottle.jpg",
    description: "A romantic floral bouquet that celebrates the timeless beauty of roses.",
    notes: {
      top: ["Petitgrain", "Lemon", "Green Leaves"],
      middle: ["Rose", "Peony", "Lily of the Valley"],
      base: ["White Musk", "Cedarwood", "Amber"],
    },
    size: ["30ml", "50ml", "100ml"],
    inStock: true,
    isNew: true,
  },
  {
    id: 5,
    name: "Alsa Fragrance - Desert Storm",
    category: "men",
    price: 119.99,
    rating: 4.6,
    reviews: 78,
    image: "/alsa-desert-storm-cologne-bottle.jpg",
    description: "An intense and powerful fragrance inspired by the raw beauty of the desert.",
    notes: {
      top: ["Bergamot", "Cardamom", "Pink Pepper"],
      middle: ["Oud", "Rose", "Saffron"],
      base: ["Amber", "Musk", "Sandalwood"],
    },
    size: ["50ml", "100ml"],
    inStock: true,
  },
  {
    id: 6,
    name: "Alsa Fragrance - Mystic Rose Attar",
    category: "attars",
    price: 89.99,
    rating: 4.9,
    reviews: 145,
    image: "/alsa-mystic-rose-attar-bottle.jpg",
    description: "Pure rose attar distilled using traditional methods for an authentic experience.",
    notes: {
      top: ["Rose Petals"],
      middle: ["Damask Rose", "Bulgarian Rose"],
      base: ["Rose Absolute", "Sandalwood"],
    },
    size: ["3ml", "6ml", "12ml"],
    inStock: true,
  },
  {
    id: 7,
    name: "Alsa Fragrance - Ocean Breeze",
    category: "women",
    price: 74.99,
    rating: 4.5,
    reviews: 92,
    image: "/alsa-ocean-breeze-perfume-bottle.jpg",
    description: "A fresh aquatic fragrance that captures the essence of ocean waves.",
    notes: {
      top: ["Sea Salt", "Lemon", "Mint"],
      middle: ["Jasmine", "Lily", "Cyclamen"],
      base: ["Driftwood", "Musk", "Amber"],
    },
    size: ["30ml", "50ml", "100ml"],
    inStock: true,
  },
  {
    id: 8,
    name: "Alsa Fragrance - Signature Blend Tester",
    category: "testers",
    price: 19.99,
    rating: 4.4,
    reviews: 67,
    image: "/alsa-signature-tester-bottle.jpg",
    description: "Try our signature blend before committing to a full bottle.",
    notes: {
      top: ["Various"],
      middle: ["Mixed Notes"],
      base: ["Signature Base"],
    },
    size: ["5ml"],
    inStock: true,
    badge: "Tester",
  },
  {
    id: 9,
    name: "Alsa Fragrance - Elegant Rose",
    category: "women",
    price: 84.99,
    rating: 4.7,
    reviews: 156,
    image: "/alsa-elegant-rose-perfume-bottle.jpg",
    description: "A timeless floral fragrance with notes of Bulgarian rose and white jasmine",
    notes: {
      top: ["Bulgarian Rose", "Pink Pepper", "Bergamot"],
      middle: ["White Jasmine", "Peony", "Lily"],
      base: ["White Musk", "Sandalwood", "Amber"],
    },
    size: ["30ml", "50ml", "100ml"],
    inStock: true,
  },
  {
    id: 10,
    name: "Alsa Fragrance - Midnight Bloom",
    category: "women",
    price: 92.99,
    rating: 4.8,
    reviews: 134,
    image: "/alsa-midnight-bloom-perfume-bottle.jpg",
    description: "Mysterious and alluring with dark florals and vanilla undertones",
    notes: {
      top: ["Black Currant", "Plum", "Bergamot"],
      middle: ["Dark Rose", "Violet", "Iris"],
      base: ["Vanilla", "Patchouli", "Dark Musk"],
    },
    size: ["30ml", "50ml", "100ml"],
    inStock: true,
    isNew: true,
  },
  {
    id: 11,
    name: "Alsa Fragrance - Crystal Essence",
    category: "women",
    price: 76.99,
    rating: 4.6,
    reviews: 98,
    image: "/alsa-crystal-essence-perfume-bottle.jpg",
    description: "Fresh and sparkling with citrus top notes and white musk base",
    notes: {
      top: ["Lemon", "Grapefruit", "Green Apple"],
      middle: ["White Tea", "Freesia", "Water Lily"],
      base: ["White Musk", "Cedar", "Crystal Amber"],
    },
    size: ["30ml", "50ml", "100ml"],
    inStock: true,
  },
  {
    id: 12,
    name: "Alsa Fragrance - Golden Orchid",
    category: "women",
    price: 118.99,
    rating: 4.9,
    reviews: 87,
    image: "/alsa-golden-orchid-perfume-bottle.jpg",
    description: "Luxurious and exotic with rare orchid extracts and amber",
    notes: {
      top: ["Golden Orchid", "Mandarin", "Pink Pepper"],
      middle: ["Exotic Orchid", "Ylang Ylang", "Tuberose"],
      base: ["Golden Amber", "Vanilla", "Precious Woods"],
    },
    size: ["50ml", "100ml"],
    inStock: true,
    badge: "Luxury",
  },
  {
    id: 13,
    name: "Alsa Fragrance - Pearl Blossom",
    category: "women",
    price: 69.99,
    rating: 4.5,
    reviews: 112,
    image: "/alsa-pearl-blossom-perfume-bottle.jpg",
    description: "Delicate and feminine with cherry blossom and soft woods",
    notes: {
      top: ["Cherry Blossom", "Pear", "Lemon"],
      middle: ["Peach Blossom", "Rose Petals", "Magnolia"],
      base: ["Soft Woods", "White Musk", "Powdery Notes"],
    },
    size: ["30ml", "50ml", "100ml"],
    inStock: true,
  },
  {
    id: 14,
    name: "Alsa Fragrance - Velvet Dreams",
    category: "women",
    price: 104.99,
    rating: 4.8,
    reviews: 145,
    image: "/alsa-velvet-dreams-perfume-bottle.jpg",
    description: "Rich and sensual with velvet rose and dark chocolate notes",
    notes: {
      top: ["Velvet Rose", "Black Cherry", "Pink Pepper"],
      middle: ["Dark Chocolate", "Plum", "Violet"],
      base: ["Velvet Musk", "Sandalwood", "Amber"],
    },
    size: ["50ml", "100ml"],
    inStock: true,
    badge: "Sensual",
  },
  {
    id: 15,
    name: "Alsa Fragrance - Titan Force",
    category: "men",
    price: 89.99,
    rating: 4.7,
    reviews: 167,
    image: "/alsa-titan-cologne-bottle.jpg",
    description: "Bold and powerful masculine fragrance for the modern warrior",
    notes: {
      top: ["Black Pepper", "Grapefruit", "Cardamom"],
      middle: ["Lavender", "Geranium", "Clary Sage"],
      base: ["Vetiver", "Cedar", "Dark Musk"],
    },
    size: ["50ml", "100ml"],
    inStock: true,
  },
  {
    id: 16,
    name: "Alsa Fragrance - Storm Rider",
    category: "men",
    price: 94.99,
    rating: 4.6,
    reviews: 134,
    image: "/alsa-storm-rider-cologne-bottle.jpg",
    description: "Dynamic and energetic with fresh aquatic and woody notes",
    notes: {
      top: ["Sea Breeze", "Bergamot", "Mint"],
      middle: ["Marine Notes", "Lavender", "Rosemary"],
      base: ["Driftwood", "Ambergris", "White Musk"],
    },
    size: ["50ml", "100ml"],
    inStock: true,
    isNew: true,
    badge: "New",
  },
  {
    id: 17,
    name: "Alsa Fragrance - Royal Knight",
    category: "men",
    price: 124.99,
    rating: 4.8,
    reviews: 98,
    image: "/alsa-royal-knight-cologne-bottle.jpg",
    description: "Noble and distinguished with rich oud and spices",
    notes: {
      top: ["Saffron", "Cardamom", "Bergamot"],
      middle: ["Oud", "Rose", "Cinnamon"],
      base: ["Amber", "Sandalwood", "Leather"],
    },
    size: ["50ml", "100ml"],
    inStock: true,
    badge: "Premium",
  },
  {
    id: 18,
    name: "Alsa Fragrance - Urban Edge",
    category: "men",
    price: 72.99,
    rating: 4.5,
    reviews: 189,
    image: "/alsa-urban-edge-cologne-bottle.jpg",
    description: "Contemporary and fresh for the urban professional",
    notes: {
      top: ["Lemon", "Apple", "Mint"],
      middle: ["Geranium", "Lavender", "Tonka Bean"],
      base: ["Cedar", "Vetiver", "Musk"],
    },
    size: ["50ml", "100ml"],
    inStock: true,
  },
  {
    id: 19,
    name: "Alsa Fragrance - Midnight Hunter",
    category: "men",
    price: 99.99,
    rating: 4.7,
    reviews: 156,
    image: "/alsa-midnight-hunter-cologne-bottle.jpg",
    description: "Intense and mysterious for evening adventures",
    notes: {
      top: ["Black Pepper", "Ginger", "Lemon"],
      middle: ["Tobacco", "Leather", "Spices"],
      base: ["Dark Woods", "Amber", "Musk"],
    },
    size: ["50ml", "100ml"],
    inStock: true,
  },
  {
    id: 20,
    name: "Alsa Fragrance - Silver Arrow",
    category: "men",
    price: 84.99,
    rating: 4.6,
    reviews: 123,
    image: "/alsa-silver-arrow-cologne-bottle.jpg",
    description: "Sharp and precise with metallic and woody accords",
    notes: {
      top: ["Silver Citrus", "Pink Pepper", "Mint"],
      middle: ["Metallic Notes", "Lavender", "Sage"],
      base: ["Steel Woods", "Vetiver", "Clean Musk"],
    },
    size: ["50ml", "100ml"],
    inStock: true,
  },
  {
    id: 21,
    name: "Alsa Fragrance - Sacred Sandalwood Attar",
    category: "attars",
    price: 79.99,
    rating: 4.9,
    reviews: 167,
    image: "/alsa-sacred-sandalwood-attar-bottle.jpg",
    description: "Pure sandalwood attar from the sacred forests of India",
    notes: {
      top: ["Sandalwood"],
      middle: ["Mysore Sandalwood", "Rose"],
      base: ["Pure Sandalwood Oil", "Amber"],
    },
    size: ["3ml", "6ml", "12ml"],
    inStock: true,
    badge: "Sacred",
  },
  {
    id: 22,
    name: "Alsa Fragrance - Golden Amber Attar",
    category: "attars",
    price: 94.99,
    rating: 4.8,
    reviews: 134,
    image: "/alsa-golden-amber-attar-bottle.jpg",
    description: "Rich golden amber attar with warm and resinous notes",
    notes: {
      top: ["Golden Amber"],
      middle: ["Benzoin", "Labdanum"],
      base: ["Amber Resin", "Vanilla"],
    },
    size: ["3ml", "6ml", "12ml"],
    inStock: true,
  },
  {
    id: 23,
    name: "Alsa Fragrance - White Musk Attar",
    category: "attars",
    price: 69.99,
    rating: 4.7,
    reviews: 198,
    image: "/alsa-white-musk-attar-bottle.jpg",
    description: "Clean and pure white musk attar for daily wear",
    notes: {
      top: ["White Musk"],
      middle: ["Clean Musk", "Soft Florals"],
      base: ["Pure Musk", "Powdery Notes"],
    },
    size: ["3ml", "6ml", "12ml"],
    inStock: true,
  },
  {
    id: 24,
    name: "Alsa Fragrance - Jasmine Night Attar",
    category: "attars",
    price: 84.99,
    rating: 4.8,
    reviews: 145,
    image: "/alsa-jasmine-night-attar-bottle.jpg",
    description: "Intoxicating jasmine attar captured at midnight bloom",
    notes: {
      top: ["Night Jasmine"],
      middle: ["Jasmine Absolute", "Rose"],
      base: ["Jasmine Oil", "Sandalwood"],
    },
    size: ["3ml", "6ml", "12ml"],
    inStock: true,
    isNew: true,
  },
  {
    id: 25,
    name: "Alsa Fragrance - Royal Saffron Attar",
    category: "attars",
    price: 129.99,
    rating: 4.9,
    reviews: 87,
    image: "/alsa-royal-saffron-attar-bottle.jpg",
    description: "Precious saffron attar fit for royalty",
    notes: {
      top: ["Kashmir Saffron"],
      middle: ["Rose", "Saffron Threads"],
      base: ["Saffron Oil", "Amber"],
    },
    size: ["3ml", "6ml"],
    inStock: true,
    badge: "Royal",
  },
  {
    id: 26,
    name: "Alsa Fragrance - Black Oud Attar",
    category: "attars",
    price: 199.99,
    rating: 4.9,
    reviews: 76,
    image: "/alsa-black-oud-attar-bottle.jpg",
    description: "Rare black oud attar from ancient agarwood trees",
    notes: {
      top: ["Black Oud"],
      middle: ["Aged Oud", "Rose"],
      base: ["Pure Oud Oil", "Amber"],
    },
    size: ["3ml", "6ml"],
    inStock: true,
    badge: "Rare",
  },
  {
    id: 27,
    name: "Alsa Fragrance - Women's Collection Tester Set",
    category: "testers",
    price: 29.99,
    rating: 4.6,
    reviews: 234,
    image: "/alsa-womens-tester-set.jpg",
    description: "Sample our entire women's fragrance collection",
    notes: {
      top: ["Various Floral"],
      middle: ["Mixed Bouquet"],
      base: ["Assorted Base Notes"],
    },
    size: ["5ml x 6"],
    inStock: true,
    badge: "Set",
  },
  {
    id: 28,
    name: "Alsa Fragrance - Men's Collection Tester Set",
    category: "testers",
    price: 29.99,
    rating: 4.5,
    reviews: 198,
    image: "/alsa-mens-tester-set.jpg",
    description: "Discover our complete men's fragrance range",
    notes: {
      top: ["Various Citrus"],
      middle: ["Mixed Spices"],
      base: ["Assorted Woods"],
    },
    size: ["5ml x 6"],
    inStock: true,
    badge: "Set",
  },
  {
    id: 29,
    name: "Alsa Fragrance - Attar Discovery Set",
    category: "testers",
    price: 39.99,
    rating: 4.8,
    reviews: 167,
    image: "/alsa-attar-discovery-set.jpg",
    description: "Experience the world of traditional attars",
    notes: {
      top: ["Various Oils"],
      middle: ["Traditional Blends"],
      base: ["Pure Essences"],
    },
    size: ["2ml x 8"],
    inStock: true,
    badge: "Discovery",
  },
  {
    id: 30,
    name: "Alsa Fragrance - Seasonal Tester",
    category: "testers",
    price: 14.99,
    rating: 4.4,
    reviews: 145,
    image: "/alsa-seasonal-tester.jpg",
    description: "Try our limited seasonal fragrance",
    notes: {
      top: ["Seasonal Notes"],
      middle: ["Limited Blend"],
      base: ["Exclusive Base"],
    },
    size: ["5ml"],
    inStock: true,
    badge: "Limited Edition",
  },
  {
    id: 31,
    name: "Alsa Fragrance - Premium Tester Collection",
    category: "testers",
    price: 49.99,
    rating: 4.7,
    reviews: 123,
    image: "/alsa-premium-tester-collection.jpg",
    description: "Sample our most exclusive premium fragrances",
    notes: {
      top: ["Premium Extracts"],
      middle: ["Luxury Blends"],
      base: ["Rare Ingredients"],
    },
    size: ["3ml x 10"],
    inStock: true,
    badge: "Premium",
  },
  {
    id: 32,
    name: "Alsa Fragrance - Travel Tester Kit",
    category: "testers",
    price: 24.99,
    rating: 4.5,
    reviews: 189,
    image: "/alsa-travel-tester-kit.jpg",
    description: "Perfect travel-sized samples for on-the-go",
    notes: {
      top: ["Travel Friendly"],
      middle: ["Portable Blends"],
      base: ["Compact Essences"],
    },
    size: ["2ml x 12"],
    inStock: true,
    badge: "Travel",
  },
  {
    id: 33,
    name: "Alsa Fragrance - Aurora Dreams",
    category: "women",
    price: 129.99,
    rating: 4.9,
    reviews: 45,
    image: "/alsa-aurora-dreams-perfume-bottle.jpg",
    description: "Ethereal and magical fragrance inspired by the northern lights",
    notes: {
      top: ["Starfruit", "Icy Mint", "Silver Citrus"],
      middle: ["Aurora Florals", "Cosmic Rose", "Celestial Jasmine"],
      base: ["Stardust Musk", "Crystalline Amber", "Moonbeam Woods"],
    },
    size: ["50ml", "100ml"],
    inStock: true,
    isNew: true,
    badge: "New",
  },
  {
    id: 34,
    name: "Alsa Fragrance - Velvet Nights",
    category: "men",
    price: 114.99,
    rating: 4.8,
    reviews: 67,
    image: "/alsa-velvet-nights-cologne-bottle.jpg",
    description: "Sophisticated evening fragrance with rich velvet undertones",
    notes: {
      top: ["Dark Bergamot", "Black Pepper", "Midnight Spices"],
      middle: ["Velvet Rose", "Smoky Incense", "Dark Chocolate"],
      base: ["Velvet Musk", "Ebony Wood", "Liquid Amber"],
    },
    size: ["50ml", "100ml"],
    inStock: true,
    isNew: true,
    badge: "New",
  },
  {
    id: 35,
    name: "Alsa Fragrance - Golden Sands Attar",
    category: "attars",
    price: 159.99,
    rating: 4.9,
    reviews: 34,
    image: "/alsa-golden-sands-attar-bottle.jpg",
    description: "Precious attar capturing the essence of desert golden sands",
    notes: {
      top: ["Desert Rose", "Golden Saffron"],
      middle: ["Warm Sand", "Amber Crystals", "Honey"],
      base: ["Golden Oud", "Sandalwood", "Precious Resins"],
    },
    size: ["3ml", "6ml", "12ml"],
    inStock: true,
    isNew: true,
    badge: "New",
  },
  {
    id: 36,
    name: "Alsa Fragrance - Crystal Waters",
    category: "women",
    price: 89.99,
    rating: 4.7,
    reviews: 78,
    image: "/alsa-crystal-waters-perfume-bottle.jpg",
    description: "Pure and refreshing like crystal clear mountain springs",
    notes: {
      top: ["Crystal Mint", "Glacier Water", "Pure Citrus"],
      middle: ["Water Lily", "Transparent Florals", "Ice Crystals"],
      base: ["Clear Musk", "Crystalline Woods", "Pure Amber"],
    },
    size: ["30ml", "50ml", "100ml"],
    inStock: true,
    isNew: true,
    badge: "New",
  },
  {
    id: 37,
    name: "Alsa Fragrance - Luxury Carry Bag (Black)",
    category: "accessories",
    price: 29.99,
    rating: 4.6,
    reviews: 156,
    image: "/alsa-luxury-carry-bag-black.jpg",
    description: "Premium black leather carry bag with Alsa Fragrance branding",
    notes: {
      top: ["Premium Leather"],
      middle: ["Elegant Design"],
      base: ["Luxury Finish"],
    },
    size: ["Medium", "Large"],
    inStock: true,
    isNew: true,
    badge: "Accessory",
  },
  {
    id: 38,
    name: "Alsa Fragrance - Luxury Carry Bag (Gold)",
    category: "accessories",
    price: 34.99,
    rating: 4.8,
    reviews: 89,
    image: "/alsa-luxury-carry-bag-gold.jpg",
    description: "Luxurious gold carry bag perfect for gifting Alsa fragrances",
    notes: {
      top: ["Gold Finish"],
      middle: ["Premium Materials"],
      base: ["Elegant Handles"],
    },
    size: ["Medium", "Large"],
    inStock: true,
    isNew: true,
    badge: "Accessory",
  },
  {
    id: 39,
    name: "Alsa Fragrance - Diamond Essence Limited",
    category: "women",
    price: 299.99,
    rating: 5.0,
    reviews: 23,
    image: "/alsa-diamond-essence-limited-bottle.jpg",
    description: "Ultra-rare diamond-infused fragrance with crystalline bottle design",
    notes: {
      top: ["Diamond Dust", "Platinum Rose", "Crystal Bergamot"],
      middle: ["Rare Orchid", "Diamond Petals", "Precious Jasmine"],
      base: ["Liquid Diamond", "Pure Amber", "Crystalline Musk"],
    },
    size: ["50ml"],
    inStock: true,
    badge: "Limited Edition",
  },
  {
    id: 40,
    name: "Alsa Fragrance - Midnight Royalty Limited",
    category: "men",
    price: 349.99,
    rating: 5.0,
    reviews: 18,
    image: "/alsa-midnight-royalty-limited-bottle.jpg",
    description: "Exclusive royal fragrance in handcrafted obsidian bottle",
    notes: {
      top: ["Royal Saffron", "Black Diamond", "Midnight Spices"],
      middle: ["King's Oud", "Royal Rose", "Noble Incense"],
      base: ["Throne Woods", "Royal Amber", "Sovereign Musk"],
    },
    size: ["50ml"],
    inStock: true,
    badge: "Limited Edition",
  },
  {
    id: 41,
    name: "Alsa Fragrance - Golden Phoenix Limited",
    category: "attars",
    price: 499.99,
    rating: 5.0,
    reviews: 12,
    image: "/alsa-golden-phoenix-limited-bottle.jpg",
    description: "Legendary attar in 24k gold-plated phoenix bottle",
    notes: {
      top: ["Phoenix Fire", "Golden Saffron", "Rare Spices"],
      middle: ["Mythical Oud", "Phoenix Rose", "Sacred Amber"],
      base: ["Eternal Gold", "Phoenix Musk", "Immortal Woods"],
    },
    size: ["6ml", "12ml"],
    inStock: true,
    badge: "Limited Edition",
  },
  {
    id: 42,
    name: "Alsa Fragrance - Celestial Dreams Limited",
    category: "women",
    price: 279.99,
    rating: 5.0,
    reviews: 31,
    image: "/alsa-celestial-dreams-limited-bottle.jpg",
    description: "Heavenly fragrance in star-shaped crystal bottle",
    notes: {
      top: ["Stardust", "Celestial Mint", "Cosmic Citrus"],
      middle: ["Galaxy Rose", "Nebula Jasmine", "Stellar Florals"],
      base: ["Moonbeam Musk", "Cosmic Amber", "Starlight Woods"],
    },
    size: ["50ml"],
    inStock: true,
    badge: "Limited Edition",
  },
  {
    id: 43,
    name: "Alsa Fragrance - Enchanted Garden",
    category: "women",
    price: 87.99,
    rating: 4.7,
    reviews: 142,
    image: "/alsa-enchanted-garden-perfume-bottle.jpg",
    description: "A magical floral journey through an enchanted garden",
    notes: {
      top: ["Wild Berries", "Dewdrops", "Morning Mist"],
      middle: ["Enchanted Rose", "Fairy Jasmine", "Magic Lily"],
      base: ["Mystical Woods", "Fairy Dust", "Enchanted Musk"],
    },
    size: ["30ml", "50ml", "100ml"],
    inStock: true,
  },
  {
    id: 44,
    name: "Alsa Fragrance - Silk Petals",
    category: "women",
    price: 92.99,
    rating: 4.8,
    reviews: 167,
    image: "/alsa-silk-petals-perfume-bottle.jpg",
    description: "Luxurious and soft like silk petals on skin",
    notes: {
      top: ["Silk Rose", "Peach Blossom", "Soft Citrus"],
      middle: ["Silk Jasmine", "Velvet Peony", "Satin Lily"],
      base: ["Silk Musk", "Cashmere Woods", "Powdery Vanilla"],
    },
    size: ["30ml", "50ml", "100ml"],
    inStock: true,
    isNew: true,
  },
  {
    id: 45,
    name: "Alsa Fragrance - Moonlight Serenade",
    category: "women",
    price: 98.99,
    rating: 4.9,
    reviews: 134,
    image: "/alsa-moonlight-serenade-perfume-bottle.jpg",
    description: "Romantic and dreamy fragrance for moonlit evenings",
    notes: {
      top: ["Moonbeam", "Silver Bergamot", "Night Blooming Cereus"],
      middle: ["Midnight Rose", "Lunar Jasmine", "Starlight Orchid"],
      base: ["Moonstone Musk", "Celestial Amber", "Dreamy Sandalwood"],
    },
    size: ["50ml", "100ml"],
    inStock: true,
  },
  {
    id: 46,
    name: "Alsa Fragrance - Cherry Blossom Dreams",
    category: "women",
    price: 79.99,
    rating: 4.6,
    reviews: 198,
    image: "/alsa-cherry-blossom-dreams-perfume-bottle.jpg",
    description: "Delicate cherry blossom fragrance from Japanese gardens",
    notes: {
      top: ["Cherry Blossom", "Pink Grapefruit", "Spring Breeze"],
      middle: ["Sakura Petals", "White Tea", "Lotus Flower"],
      base: ["Soft Woods", "Clean Musk", "Zen Amber"],
    },
    size: ["30ml", "50ml", "100ml"],
    inStock: true,
  },
  {
    id: 47,
    name: "Alsa Fragrance - Diamond Dust",
    category: "women",
    price: 124.99,
    rating: 4.8,
    reviews: 89,
    image: "/alsa-diamond-dust-perfume-bottle.jpg",
    description: "Sparkling and brilliant like precious diamonds",
    notes: {
      top: ["Diamond Sparkle", "Crystal Citrus", "Platinum Rose"],
      middle: ["Diamond Petals", "Precious Jasmine", "Crystal Orchid"],
      base: ["Diamond Musk", "Crystalline Amber", "Precious Woods"],
    },
    size: ["50ml", "100ml"],
    inStock: true,
    badge: "Luxury",
  },
  {
    id: 48,
    name: "Alsa Fragrance - Tropical Paradise",
    category: "women",
    price: 84.99,
    rating: 4.7,
    reviews: 156,
    image: "/alsa-tropical-paradise-perfume-bottle.jpg",
    description: "Escape to a tropical paradise with exotic florals",
    notes: {
      top: ["Tropical Fruits", "Coconut Water", "Island Breeze"],
      middle: ["Frangipani", "Tropical Jasmine", "Hibiscus"],
      base: ["Driftwood", "Tropical Musk", "Sunset Amber"],
    },
    size: ["30ml", "50ml", "100ml"],
    inStock: true,
  },
  {
    id: 49,
    name: "Alsa Fragrance - Lavender Fields",
    category: "women",
    price: 74.99,
    rating: 4.5,
    reviews: 223,
    image: "/alsa-lavender-fields-perfume-bottle.jpg",
    description: "Calming lavender fields of Provence",
    notes: {
      top: ["French Lavender", "Bergamot", "Lemon"],
      middle: ["Lavender Absolute", "Geranium", "Rosemary"],
      base: ["Lavender Woods", "Soft Musk", "Herbal Amber"],
    },
    size: ["30ml", "50ml", "100ml"],
    inStock: true,
  },
  {
    id: 50,
    name: "Alsa Fragrance - Golden Honey",
    category: "women",
    price: 89.99,
    rating: 4.8,
    reviews: 178,
    image: "/alsa-golden-honey-perfume-bottle.jpg",
    description: "Sweet and warm like golden honey from wildflowers",
    notes: {
      top: ["Golden Honey", "Orange Blossom", "Wildflowers"],
      middle: ["Honey Absolute", "Acacia", "Bee Pollen"],
      base: ["Honeycomb", "Warm Amber", "Creamy Vanilla"],
    },
    size: ["30ml", "50ml", "100ml"],
    inStock: true,
  },
  {
    id: 51,
    name: "Alsa Fragrance - Mystic Violet",
    category: "women",
    price: 94.99,
    rating: 4.7,
    reviews: 145,
    image: "/alsa-mystic-violet-perfume-bottle.jpg",
    description: "Mysterious and enchanting violet fragrance",
    notes: {
      top: ["Mystic Violet", "Purple Berries", "Iris"],
      middle: ["Violet Absolute", "Purple Rose", "Amethyst Florals"],
      base: ["Violet Musk", "Purple Woods", "Mystical Amber"],
    },
    size: ["50ml", "100ml"],
    inStock: true,
  },
  {
    id: 52,
    name: "Alsa Fragrance - White Tea Serenity",
    category: "women",
    price: 82.99,
    rating: 4.6,
    reviews: 167,
    image: "/alsa-white-tea-serenity-perfume-bottle.jpg",
    description: "Peaceful and serene white tea fragrance",
    notes: {
      top: ["White Tea", "Green Citrus", "Fresh Mint"],
      middle: ["Tea Leaves", "White Florals", "Zen Garden"],
      base: ["Tea Woods", "Serene Musk", "Peaceful Amber"],
    },
    size: ["30ml", "50ml", "100ml"],
    inStock: true,
  },
  {
    id: 53,
    name: "Alsa Fragrance - Crimson Rose",
    category: "women",
    price: 99.99,
    rating: 4.9,
    reviews: 134,
    image: "/alsa-crimson-rose-perfume-bottle.jpg",
    description: "Deep crimson roses in full bloom",
    notes: {
      top: ["Crimson Rose", "Red Berries", "Pink Pepper"],
      middle: ["Rose Absolute", "Red Peony", "Crimson Petals"],
      base: ["Rose Woods", "Deep Musk", "Crimson Amber"],
    },
    size: ["50ml", "100ml"],
    inStock: true,
    badge: "Signature",
  },
  {
    id: 54,
    name: "Alsa Fragrance - Vanilla Orchid",
    category: "women",
    price: 104.99,
    rating: 4.8,
    reviews: 156,
    image: "/alsa-vanilla-orchid-perfume-bottle.jpg",
    description: "Exotic vanilla orchid from Madagascar",
    notes: {
      top: ["Vanilla Orchid", "Tropical Fruits", "Coconut"],
      middle: ["Orchid Absolute", "Vanilla Flower", "Exotic Blooms"],
      base: ["Madagascar Vanilla", "Orchid Woods", "Creamy Musk"],
    },
    size: ["50ml", "100ml"],
    inStock: true,
  },
  {
    id: 55,
    name: "Alsa Fragrance - Sapphire Nights",
    category: "women",
    price: 119.99,
    rating: 4.9,
    reviews: 98,
    image: "/alsa-sapphire-nights-perfume-bottle.jpg",
    description: "Elegant evening fragrance like precious sapphires",
    notes: {
      top: ["Sapphire Sparkle", "Night Bergamot", "Blue Rose"],
      middle: ["Sapphire Florals", "Midnight Jasmine", "Blue Orchid"],
      base: ["Sapphire Musk", "Precious Woods", "Blue Amber"],
    },
    size: ["50ml", "100ml"],
    inStock: true,
    badge: "Premium",
  },
  {
    id: 56,
    name: "Alsa Fragrance - Thunder Strike",
    category: "men",
    price: 94.99,
    rating: 4.7,
    reviews: 189,
    image: "/alsa-thunder-strike-cologne-bottle.jpg",
    description: "Powerful and electrifying like a thunder strike",
    notes: {
      top: ["Electric Citrus", "Lightning Mint", "Storm Spices"],
      middle: ["Thunder Woods", "Electric Lavender", "Storm Sage"],
      base: ["Lightning Musk", "Thunder Amber", "Electric Woods"],
    },
    size: ["50ml", "100ml"],
    inStock: true,
  },
  {
    id: 57,
    name: "Alsa Fragrance - Ocean Depths",
    category: "men",
    price: 89.99,
    rating: 4.6,
    reviews: 167,
    image: "/alsa-ocean-depths-cologne-bottle.jpg",
    description: "Deep and mysterious like ocean depths",
    notes: {
      top: ["Ocean Spray", "Sea Salt", "Marine Citrus"],
      middle: ["Deep Waters", "Seaweed", "Ocean Minerals"],
      base: ["Ocean Floor", "Deep Musk", "Aquatic Amber"],
    },
    size: ["50ml", "100ml"],
    inStock: true,
  },
  {
    id: 58,
    name: "Alsa Fragrance - Steel Warrior",
    category: "men",
    price: 104.99,
    rating: 4.8,
    reviews: 145,
    image: "/alsa-steel-warrior-cologne-bottle.jpg",
    description: "Strong and resilient like forged steel",
    notes: {
      top: ["Steel Citrus", "Metallic Spices", "Iron Mint"],
      middle: ["Steel Woods", "Metal Sage", "Warrior Herbs"],
      base: ["Forged Steel", "Metal Musk", "Steel Amber"],
    },
    size: ["50ml", "100ml"],
    inStock: true,
    badge: "Strength",
  },
  {
    id: 59,
    name: "Alsa Fragrance - Forest King",
    category: "men",
    price: 99.99,
    rating: 4.7,
    reviews: 134,
    image: "/alsa-forest-king-cologne-bottle.jpg",
    description: "Majestic and commanding like the king of the forest",
    notes: {
      top: ["Forest Berries", "Pine Needles", "Wild Mint"],
      middle: ["Cedar King", "Forest Sage", "Wild Herbs"],
      base: ["Ancient Woods", "Forest Musk", "Royal Amber"],
    },
    size: ["50ml", "100ml"],
    inStock: true,
  },
  {
    id: 60,
    name: "Alsa Fragrance - Golden Eagle",
    category: "men",
    price: 114.99,
    rating: 4.8,
    reviews: 123,
    image: "/alsa-golden-eagle-cologne-bottle.jpg",
    description: "Soaring high with golden eagle spirit",
    notes: {
      top: ["Golden Citrus", "Eagle Spices", "Mountain Air"],
      middle: ["Golden Woods", "Eagle Herbs", "Sky Sage"],
      base: ["Golden Musk", "Eagle Amber", "Soaring Woods"],
    },
    size: ["50ml", "100ml"],
    inStock: true,
    badge: "Majestic",
  },
  {
    id: 61,
    name: "Alsa Fragrance - Midnight Phantom",
    category: "men",
    price: 109.99,
    rating: 4.9,
    reviews: 98,
    image: "/alsa-midnight-phantom-cologne-bottle.jpg",
    description: "Mysterious and elusive like a midnight phantom",
    notes: {
      top: ["Phantom Spices", "Midnight Citrus", "Shadow Mint"],
      middle: ["Phantom Woods", "Midnight Herbs", "Shadow Sage"],
      base: ["Phantom Musk", "Midnight Amber", "Shadow Woods"],
    },
    size: ["50ml", "100ml"],
    inStock: true,
    isNew: true,
  },
  {
    id: 62,
    name: "Alsa Fragrance - Arctic Wolf",
    category: "men",
    price: 96.99,
    rating: 4.7,
    reviews: 156,
    image: "/alsa-arctic-wolf-cologne-bottle.jpg",
    description: "Wild and free like an arctic wolf",
    notes: {
      top: ["Arctic Mint", "Ice Citrus", "Snow Spices"],
      middle: ["Wolf Woods", "Arctic Herbs", "Ice Sage"],
      base: ["Wolf Musk", "Arctic Amber", "Ice Woods"],
    },
    size: ["50ml", "100ml"],
    inStock: true,
  },
  {
    id: 63,
    name: "Alsa Fragrance - Fire Dragon",
    category: "men",
    price: 124.99,
    rating: 4.8,
    reviews: 89,
    image: "/alsa-fire-dragon-cologne-bottle.jpg",
    description: "Fierce and powerful like a fire dragon",
    notes: {
      top: ["Dragon Fire", "Flame Spices", "Fire Citrus"],
      middle: ["Dragon Woods", "Fire Herbs", "Flame Sage"],
      base: ["Dragon Musk", "Fire Amber", "Flame Woods"],
    },
    size: ["50ml", "100ml"],
    inStock: true,
    badge: "Fierce",
  },
  {
    id: 64,
    name: "Alsa Fragrance - Mountain Peak",
    category: "men",
    price: 87.99,
    rating: 4.6,
    reviews: 178,
    image: "/alsa-mountain-peak-cologne-bottle.jpg",
    description: "Fresh and invigorating like mountain peaks",
    notes: {
      top: ["Mountain Air", "Peak Citrus", "Alpine Mint"],
      middle: ["Mountain Woods", "Peak Herbs", "Alpine Sage"],
      base: ["Mountain Musk", "Peak Amber", "Alpine Woods"],
    },
    size: ["50ml", "100ml"],
    inStock: true,
  },
  {
    id: 65,
    name: "Alsa Fragrance - Black Panther",
    category: "men",
    price: 119.99,
    rating: 4.9,
    reviews: 112,
    image: "/alsa-black-panther-cologne-bottle.jpg",
    description: "Sleek and powerful like a black panther",
    notes: {
      top: ["Black Spices", "Panther Citrus", "Dark Mint"],
      middle: ["Black Woods", "Panther Herbs", "Dark Sage"],
      base: ["Panther Musk", "Black Amber", "Dark Woods"],
    },
    size: ["50ml", "100ml"],
    inStock: true,
    badge: "Power",
  },
  {
    id: 66,
    name: "Alsa Fragrance - Solar Flare",
    category: "men",
    price: 102.99,
    rating: 4.7,
    reviews: 134,
    image: "/alsa-solar-flare-cologne-bottle.jpg",
    description: "Bright and energetic like solar flares",
    notes: {
      top: ["Solar Citrus", "Flare Spices", "Sun Mint"],
      middle: ["Solar Woods", "Flare Herbs", "Sun Sage"],
      base: ["Solar Musk", "Flare Amber", "Sun Woods"],
    },
    size: ["50ml", "100ml"],
    inStock: true,
  },
  {
    id: 67,
    name: "Alsa Fragrance - Iron Fortress",
    category: "men",
    price: 91.99,
    rating: 4.6,
    reviews: 167,
    image: "/alsa-iron-fortress-cologne-bottle.jpg",
    description: "Strong and protective like an iron fortress",
    notes: {
      top: ["Iron Citrus", "Fortress Spices", "Metal Mint"],
      middle: ["Iron Woods", "Fortress Herbs", "Metal Sage"],
      base: ["Iron Musk", "Fortress Amber", "Metal Woods"],
    },
    size: ["50ml", "100ml"],
    inStock: true,
  },
  {
    id: 68,
    name: "Alsa Fragrance - Crimson Knight",
    category: "men",
    price: 134.99,
    rating: 4.8,
    reviews: 98,
    image: "/alsa-crimson-knight-cologne-bottle.jpg",
    description: "Noble and brave like a crimson knight",
    notes: {
      top: ["Crimson Spices", "Knight Citrus", "Red Mint"],
      middle: ["Crimson Woods", "Knight Herbs", "Red Sage"],
      base: ["Knight Musk", "Crimson Amber", "Red Woods"],
    },
    size: ["50ml", "100ml"],
    inStock: true,
    badge: "Noble",
  },
  {
    id: 69,
    name: "Alsa Fragrance - Celestial Oud Attar",
    category: "attars",
    price: 189.99,
    rating: 4.9,
    reviews: 76,
    image: "/alsa-celestial-oud-attar-bottle.jpg",
    description: "Divine oud attar from celestial agarwood",
    notes: {
      top: ["Celestial Oud", "Star Saffron"],
      middle: ["Divine Oud", "Heavenly Rose", "Sacred Amber"],
      base: ["Pure Oud Oil", "Celestial Musk", "Divine Woods"],
    },
    size: ["3ml", "6ml", "12ml"],
    inStock: true,
    badge: "Divine",
  },
  {
    id: 70,
    name: "Alsa Fragrance - Rose Paradise Attar",
    category: "attars",
    price: 94.99,
    rating: 4.8,
    reviews: 145,
    image: "/alsa-rose-paradise-attar-bottle.jpg",
    description: "Paradise of roses in pure attar form",
    notes: {
      top: ["Paradise Rose", "Garden Blooms"],
      middle: ["Rose Absolute", "Paradise Petals", "Rose Garden"],
      base: ["Pure Rose Oil", "Paradise Musk", "Rose Woods"],
    },
    size: ["3ml", "6ml", "12ml"],
    inStock: true,
  },
  {
    id: 71,
    name: "Alsa Fragrance - Amber Royale Attar",
    category: "attars",
    price: 114.99,
    rating: 4.9,
    reviews: 123,
    image: "/alsa-amber-royale-attar-bottle.jpg",
    description: "Royal amber attar fit for kings",
    notes: {
      top: ["Royal Amber", "Golden Resin"],
      middle: ["Amber Absolute", "Royal Benzoin", "Golden Labdanum"],
      base: ["Pure Amber Oil", "Royal Musk", "Golden Woods"],
    },
    size: ["3ml", "6ml", "12ml"],
    inStock: true,
    badge: "Royal",
  },
  {
    id: 72,
    name: "Alsa Fragrance - Musk Al Hajar Attar",
    category: "attars",
    price: 79.99,
    rating: 4.7,
    reviews: 189,
    image: "/alsa-musk-al-hajar-attar-bottle.jpg",
    description: "Traditional musk attar from ancient recipes",
    notes: {
      top: ["Pure Musk", "Traditional Blend"],
      middle: ["Musk Absolute", "Ancient Musk", "Sacred Musk"],
      base: ["Pure Musk Oil", "Traditional Base", "Ancient Woods"],
    },
    size: ["3ml", "6ml", "12ml"],
    inStock: true,
  },
  {
    id: 73,
    name: "Alsa Fragrance - Frankincense Sacred Attar",
    category: "attars",
    price: 104.99,
    rating: 4.8,
    reviews: 134,
    image: "/alsa-frankincense-sacred-attar-bottle.jpg",
    description: "Sacred frankincense attar for spiritual moments",
    notes: {
      top: ["Sacred Frankincense", "Holy Resin"],
      middle: ["Frankincense Absolute", "Sacred Smoke", "Holy Incense"],
      base: ["Pure Frankincense Oil", "Sacred Musk", "Holy Woods"],
    },
    size: ["3ml", "6ml", "12ml"],
    inStock: true,
    badge: "Sacred",
  },
  {
    id: 74,
    name: "Alsa Fragrance - Agarwood Supreme Attar",
    category: "attars",
    price: 249.99,
    rating: 5.0,
    reviews: 67,
    image: "/alsa-agarwood-supreme-attar-bottle.jpg",
    description: "Supreme quality agarwood attar from ancient trees",
    notes: {
      top: ["Supreme Agarwood", "Ancient Oud"],
      middle: ["Agarwood Absolute", "Supreme Oud", "Ancient Resin"],
      base: ["Pure Agarwood Oil", "Supreme Musk", "Ancient Woods"],
    },
    size: ["3ml", "6ml"],
    inStock: true,
    badge: "Supreme",
  },
  {
    id: 75,
    name: "Alsa Fragrance - Jasmine Mogra Attar",
    category: "attars",
    price: 89.99,
    rating: 4.8,
    reviews: 156,
    image: "/alsa-jasmine-mogra-attar-bottle.jpg",
    description: "Pure jasmine mogra attar from night blooms",
    notes: {
      top: ["Jasmine Mogra", "Night Blooms"],
      middle: ["Jasmine Absolute", "Mogra Petals", "Night Jasmine"],
      base: ["Pure Jasmine Oil", "Mogra Musk", "Jasmine Woods"],
    },
    size: ["3ml", "6ml", "12ml"],
    inStock: true,
  },
  {
    id: 76,
    name: "Alsa Fragrance - Kesar Kasturi Attar",
    category: "attars",
    price: 139.99,
    rating: 4.9,
    reviews: 98,
    image: "/alsa-kesar-kasturi-attar-bottle.jpg",
    description: "Precious saffron and musk attar blend",
    notes: {
      top: ["Kashmir Saffron", "Pure Kasturi"],
      middle: ["Saffron Absolute", "Kasturi Musk", "Golden Threads"],
      base: ["Pure Saffron Oil", "Kasturi Base", "Golden Woods"],
    },
    size: ["3ml", "6ml", "12ml"],
    inStock: true,
    badge: "Precious",
  },
  {
    id: 77,
    name: "Alsa Fragrance - Hina Attar",
    category: "attars",
    price: 74.99,
    rating: 4.7,
    reviews: 167,
    image: "/alsa-hina-attar-bottle.jpg",
    description: "Traditional hina attar with floral essence",
    notes: {
      top: ["Hina Flowers", "Traditional Blend"],
      middle: ["Hina Absolute", "Floral Essence", "Traditional Notes"],
      base: ["Pure Hina Oil", "Traditional Musk", "Floral Woods"],
    },
    size: ["3ml", "6ml", "12ml"],
    inStock: true,
  },
  {
    id: 78,
    name: "Alsa Fragrance - Ruh Khus Attar",
    category: "attars",
    price: 69.99,
    rating: 4.6,
    reviews: 198,
    image: "/alsa-ruh-khus-attar-bottle.jpg",
    description: "Cooling ruh khus attar for summer",
    notes: {
      top: ["Ruh Khus", "Cooling Essence"],
      middle: ["Khus Absolute", "Cooling Herbs", "Fresh Roots"],
      base: ["Pure Khus Oil", "Cooling Musk", "Fresh Woods"],
    },
    size: ["3ml", "6ml", "12ml"],
    inStock: true,
    badge: "Cooling",
  },
  {
    id: 79,
    name: "Alsa Fragrance - Chameli Attar",
    category: "attars",
    price: 84.99,
    rating: 4.8,
    reviews: 145,
    image: "/alsa-chameli-attar-bottle.jpg",
    description: "Sweet chameli attar from fresh flowers",
    notes: {
      top: ["Chameli Flowers", "Sweet Blooms"],
      middle: ["Chameli Absolute", "Sweet Petals", "Fresh Flowers"],
      base: ["Pure Chameli Oil", "Sweet Musk", "Floral Woods"],
    },
    size: ["3ml", "6ml", "12ml"],
    inStock: true,
  },
  {
    id: 80,
    name: "Alsa Fragrance - Majmua Attar",
    category: "attars",
    price: 99.99,
    rating: 4.8,
    reviews: 134,
    image: "/alsa-majmua-attar-bottle.jpg",
    description: "Complex majmua blend of multiple essences",
    notes: {
      top: ["Majmua Blend", "Multiple Essences"],
      middle: ["Complex Florals", "Blended Notes", "Traditional Mix"],
      base: ["Majmua Base", "Blended Musk", "Complex Woods"],
    },
    size: ["3ml", "6ml", "12ml"],
    inStock: true,
    badge: "Complex",
  },
  {
    id: 81,
    name: "Alsa Fragrance - Signature Collection Tester",
    category: "testers",
    price: 34.99,
    rating: 4.7,
    reviews: 189,
    image: "/alsa-signature-collection-tester.jpg",
    description: "Complete signature collection in tester sizes",
    notes: {
      top: ["Signature Blends", "Premium Extracts"],
      middle: ["Collection Notes", "Signature Mix"],
      base: ["Signature Base", "Premium Finish"],
    },
    size: ["3ml x 12"],
    inStock: true,
    badge: "Collection",
  },
  {
    id: 82,
    name: "Alsa Fragrance - Luxury Tester Vault",
    category: "testers",
    price: 59.99,
    rating: 4.8,
    reviews: 145,
    image: "/alsa-luxury-tester-vault.jpg",
    description: "Vault of luxury fragrances in tester form",
    notes: {
      top: ["Luxury Extracts", "Premium Oils"],
      middle: ["Vault Collection", "Luxury Blends"],
      base: ["Luxury Base", "Premium Finish"],
    },
    size: ["2ml x 20"],
    inStock: true,
    badge: "Vault",
  },
  {
    id: 83,
    name: "Alsa Fragrance - Oriental Tester Set",
    category: "testers",
    price: 44.99,
    rating: 4.7,
    reviews: 167,
    image: "/alsa-oriental-tester-set.jpg",
    description: "Oriental fragrances tester collection",
    notes: {
      top: ["Oriental Spices", "Eastern Blends"],
      middle: ["Oriental Notes", "Spice Mix"],
      base: ["Oriental Base", "Eastern Woods"],
    },
    size: ["3ml x 15"],
    inStock: true,
    badge: "Oriental",
  },
  {
    id: 84,
    name: "Alsa Fragrance - Fresh & Clean Testers",
    category: "testers",
    price: 26.99,
    rating: 4.6,
    reviews: 198,
    image: "/alsa-fresh-clean-testers.jpg",
    description: "Fresh and clean fragrances for daily wear",
    notes: {
      top: ["Fresh Citrus", "Clean Notes"],
      middle: ["Fresh Florals", "Clean Blend"],
      base: ["Fresh Base", "Clean Finish"],
    },
    size: ["5ml x 8"],
    inStock: true,
    badge: "Fresh",
  },
  {
    id: 85,
    name: "Alsa Fragrance - Evening Elegance Testers",
    category: "testers",
    price: 39.99,
    rating: 4.8,
    reviews: 134,
    image: "/alsa-evening-elegance-testers.jpg",
    description: "Elegant evening fragrances tester set",
    notes: {
      top: ["Evening Notes", "Elegant Blends"],
      middle: ["Sophisticated Mix", "Evening Florals"],
      base: ["Elegant Base", "Evening Woods"],
    },
    size: ["3ml x 10"],
    inStock: true,
    badge: "Evening",
  },
  {
    id: 86,
    name: "Alsa Fragrance - Seasonal Favorites Testers",
    category: "testers",
    price: 32.99,
    rating: 4.7,
    reviews: 156,
    image: "/alsa-seasonal-favorites-testers.jpg",
    description: "Seasonal favorite fragrances collection",
    notes: {
      top: ["Seasonal Notes", "Favorite Blends"],
      middle: ["Season Mix", "Popular Notes"],
      base: ["Seasonal Base", "Favorite Finish"],
    },
    size: ["4ml x 8"],
    inStock: true,
    badge: "Seasonal",
  },
  {
    id: 87,
    name: "Alsa Fragrance - Unisex Tester Collection",
    category: "testers",
    price: 37.99,
    rating: 4.6,
    reviews: 178,
    image: "/alsa-unisex-tester-collection.jpg",
    description: "Unisex fragrances for everyone",
    notes: {
      top: ["Unisex Notes", "Balanced Blends"],
      middle: ["Gender Neutral", "Universal Appeal"],
      base: ["Unisex Base", "Balanced Finish"],
    },
    size: ["3ml x 12"],
    inStock: true,
    badge: "Unisex",
  },
  {
    id: 88,
    name: "Alsa Fragrance - Rare Finds Tester Set",
    category: "testers",
    price: 54.99,
    rating: 4.9,
    reviews: 98,
    image: "/alsa-rare-finds-tester-set.jpg",
    description: "Rare and unique fragrances tester collection",
    notes: {
      top: ["Rare Extracts", "Unique Blends"],
      middle: ["Rare Notes", "Unique Mix"],
      base: ["Rare Base", "Unique Finish"],
    },
    size: ["2ml x 15"],
    inStock: true,
    badge: "Rare",
  },
  {
    id: 89,
    name: "Alsa Fragrance - Bestsellers Tester Pack",
    category: "testers",
    price: 29.99,
    rating: 4.7,
    reviews: 223,
    image: "/alsa-bestsellers-tester-pack.jpg",
    description: "Our bestselling fragrances in tester sizes",
    notes: {
      top: ["Bestseller Notes", "Popular Blends"],
      middle: ["Top Sellers", "Popular Mix"],
      base: ["Bestseller Base", "Popular Finish"],
    },
    size: ["5ml x 6"],
    inStock: true,
    badge: "Bestsellers",
  },
  {
    id: 90,
    name: "Alsa Fragrance - Mood Collection Testers",
    category: "testers",
    price: 41.99,
    rating: 4.8,
    reviews: 145,
    image: "/alsa-mood-collection-testers.jpg",
    description: "Fragrances for every mood and occasion",
    notes: {
      top: ["Mood Notes", "Occasion Blends"],
      middle: ["Emotional Mix", "Mood Enhancers"],
      base: ["Mood Base", "Emotional Finish"],
    },
    size: ["3ml x 14"],
    inStock: true,
    badge: "Mood",
  },
]

export function getProductsByCategory(category: string) {
  return products.filter((product) => product.category === category)
}

export function getProductById(id: number) {
  return products.find((product) => product.id === id)
}

export function getFeaturedProducts() {
  return [
    products.find((p) => p.id === 1), // Midnight Elegance (women, sale)
    products.find((p) => p.id === 2), // Royal Oud (attars, premium)
    products.find((p) => p.id === 3), // Urban Legend (men)
    products.find((p) => p.id === 12), // Golden Orchid (women, luxury)
    products.find((p) => p.id === 17), // Royal Knight (men, premium)
    products.find((p) => p.id === 25), // Royal Saffron Attar (attars, royal)
    products.find((p) => p.id === 39), // Diamond Essence Limited (women, limited)
    products.find((p) => p.id === 40), // Midnight Royalty Limited (men, limited)
  ].filter(Boolean)
}

export function searchProducts(query: string) {
  return products.filter(
    (product) =>
      product.name.toLowerCase().includes(query.toLowerCase()) ||
      product.description.toLowerCase().includes(query.toLowerCase()) ||
      product.category.toLowerCase().includes(query.toLowerCase()),
  )
}

export function getNewArrivals() {
  return products.filter((product) => product.isNew === true && product.category !== "accessories").slice(0, 12)
}

export function getLimitedEditionProducts() {
  return products.filter((product) => product.badge === "Limited Edition")
}

export default products
