export interface Product {
  id: number
  name: string
  category: "women" | "men" | "attars" | "testers" | "accessories"
  price: number
  originalPrice?: number
  rating: number
  reviews: number
  image: string
  images?: string[]
  description: string
  notes: {
    top: string[]
    middle: string[]
    base: string[]
  }
  size: string[]
  inStock: boolean
  isNew?: boolean
  isSale?: boolean
  badge?: string
}

export const products: Product[] = [
  // WOMEN'S FRAGRANCES
  {
    id: 1,
    name: "Alsa Fragrance - Midnight Elegance",
    category: "women",
    price: 1,
    originalPrice: 1,
    rating: 4.8,
    reviews: 124,
    image: "/elegant-black-perfume-bottle-with-gold-alsa-fragra.jpg",
    description: "A sophisticated evening fragrance that captures the essence of mystery and allure.",
    notes: {
      top: ["Bergamot", "Black Currant", "Pink Pepper"],
      middle: ["Rose", "Jasmine", "Violet"],
      base: ["Vanilla", "Musk", "Sandalwood"],
    },
    size: ["30ml", "50ml", "100ml"],
    inStock: true,
    isSale: true,
    badge: "Sale",
  },
  {
    id: 2,
    name: "Alsa Fragrance - Rose Garden",
    category: "women",
    price: 1,
    rating: 4.8,
    reviews: 203,
    image: "/pink-rose-gold-perfume-bottle-with-alsa-fragrance-.jpg",
    description: "A romantic floral bouquet that celebrates the timeless beauty of roses.",
    notes: {
      top: ["Petitgrain", "Lemon", "Green Leaves"],
      middle: ["Rose", "Peony", "Lily of the Valley"],
      base: ["White Musk", "Cedarwood", "Amber"],
    },
    size: ["30ml", "50ml", "100ml"],
    inStock: true,
    isNew: true,
  },
  {
    id: 3,
    name: "Alsa Fragrance - Crystal Dreams",
    category: "women",
    price: 1,
    rating: 4.9,
    reviews: 167,
    image: "/crystal-clear-perfume-bottle-with-silver-alsa-frag.jpg",
    description: "A luminous fragrance that sparkles with crystalline freshness and ethereal beauty.",
    notes: {
      top: ["Mandarin", "Water Lily", "Freesia"],
      middle: ["Magnolia", "Lotus", "White Tea"],
      base: ["Crystal Musk", "Blonde Woods", "Soft Amber"],
    },
    size: ["30ml", "50ml", "100ml"],
    inStock: true,
    badge: "Limited Edition",
  },
  {
    id: 4,
    name: "Alsa Fragrance - Velvet Orchid",
    category: "women",
    price: 1,
    rating: 4.7,
    reviews: 145,
    image: "/deep-purple-velvet-perfume-bottle-with-gold-alsa-f.jpg",
    description: "An opulent floral oriental fragrance with the exotic allure of rare orchids.",
    notes: {
      top: ["Black Truffle", "Bergamot", "Honey"],
      middle: ["Black Orchid", "Lotus", "Spicy Notes"],
      base: ["Patchouli", "Vanilla", "Balsam"],
    },
    size: ["30ml", "50ml", "100ml"],
    inStock: true,
    badge: "Premium",
  },
  {
    id: 5,
    name: "Alsa Fragrance - Golden Sunset",
    category: "women",
    price: 1,
    originalPrice: 1,
    rating: 4.6,
    reviews: 189,
    image: "/golden-amber-perfume-bottle-with-alsa-fragrance-lo.jpg",
    description: "A warm, radiant fragrance that captures the golden hour's magical glow.",
    notes: {
      top: ["Orange Blossom", "Peach", "Ginger"],
      middle: ["Tuberose", "Ylang-Ylang", "Coconut"],
      base: ["Amber", "Sandalwood", "Tonka Bean"],
    },
    size: ["30ml", "50ml", "100ml"],
    inStock: true,
    isSale: true,
  },
  {
    id: 6,
    name: "Alsa Fragrance - Moonlight Serenade",
    category: "women",
    price: 1,
    rating: 4.8,
    reviews: 156,
    image: "/silver-moonlight-perfume-bottle-with-alsa-fragranc.jpg",
    description: "A dreamy nocturnal fragrance that whispers of moonlit romance.",
    notes: {
      top: ["Night Blooming Jasmine", "Silver Linden", "Dewdrops"],
      middle: ["Moonflower", "White Rose", "Iris"],
      base: ["White Musk", "Cashmere Wood", "Soft Vanilla"],
    },
    size: ["30ml", "50ml", "100ml"],
    inStock: true,
    isNew: true,
  },
  {
    id: 7,
    name: "Alsa Fragrance - Cherry Blossom",
    category: "women",
    price: 1,
    rating: 4.5,
    reviews: 234,
    image: "/pink-cherry-blossom-perfume-bottle-with-alsa-fragr.jpg",
    description: "A delicate spring fragrance celebrating the ephemeral beauty of cherry blossoms.",
    notes: {
      top: ["Cherry Blossom", "Mandarin", "Green Leaves"],
      middle: ["Sakura", "Peony", "Lily"],
      base: ["Soft Musk", "Cedar", "Light Amber"],
    },
    size: ["30ml", "50ml", "100ml"],
    inStock: true,
  },
  {
    id: 8,
    name: "Alsa Fragrance - Emerald Garden",
    category: "women",
    price: 1,
    rating: 4.7,
    reviews: 178,
    image: "/emerald-green-perfume-bottle-with-gold-alsa-fragra.jpg",
    description: "A fresh green fragrance that captures the essence of a secret garden.",
    notes: {
      top: ["Green Mandarin", "Basil", "Mint"],
      middle: ["Green Tea", "Bamboo", "Lily of the Valley"],
      base: ["Green Musk", "Vetiver", "White Cedar"],
    },
    size: ["30ml", "50ml", "100ml"],
    inStock: true,
    badge: "Fresh",
  },
  {
    id: 28,
    name: "Alsa Fragrance - Diamond Dust",
    category: "women",
    price: 1,
    rating: 4.9,
    reviews: 89,
    image: "/placeholder.svg?height=400&width=300",
    description: "A luxurious fragrance that sparkles like precious diamonds.",
    notes: {
      top: ["Champagne", "Pink Grapefruit", "Sparkling Notes"],
      middle: ["Diamond Dust Accord", "White Flowers", "Peony"],
      base: ["Platinum Musk", "Crystal Amber", "Cashmere"],
    },
    size: ["30ml", "50ml", "100ml"],
    inStock: true,
    badge: "Luxury",
  },
  {
    id: 29,
    name: "Alsa Fragrance - Silk Whisper",
    category: "women",
    price: 1,
    rating: 4.6,
    reviews: 145,
    image: "/placeholder.svg?height=400&width=300",
    description: "A soft, sensual fragrance as smooth and luxurious as silk.",
    notes: {
      top: ["Silk Accord", "Pear", "Freesia"],
      middle: ["Silk Flower", "Magnolia", "Soft Spices"],
      base: ["Silk Musk", "Cashmere Wood", "Vanilla"],
    },
    size: ["30ml", "50ml", "100ml"],
    inStock: true,
  },
  {
    id: 30,
    name: "Alsa Fragrance - Starlight Symphony",
    category: "women",
    price: 1,
    rating: 4.8,
    reviews: 167,
    image: "/placeholder.svg?height=400&width=300",
    description: "A celestial fragrance that captures the magic of a starlit night.",
    notes: {
      top: ["Starfruit", "Cosmic Berry", "Night Air"],
      middle: ["Celestial Flowers", "Moonbeam", "Stellar Accord"],
      base: ["Cosmic Musk", "Starlight Amber", "Galaxy Woods"],
    },
    size: ["30ml", "50ml", "100ml"],
    inStock: true,
    badge: "Celestial",
  },
  {
    id: 38,
    name: "Alsa Fragrance - Phoenix Rising",
    category: "women",
    price: 1,
    rating: 4.9,
    reviews: 78,
    image: "/placeholder.svg?height=400&width=300",
    description: "A powerful fragrance that rises from the ashes like a phoenix reborn.",
    notes: {
      top: ["Fire Accord", "Spicy Ginger", "Red Pepper"],
      middle: ["Phoenix Flower", "Burning Rose", "Cinnamon"],
      base: ["Smoky Amber", "Fire Musk", "Charred Woods"],
    },
    size: ["30ml", "50ml", "100ml"],
    inStock: true,
    badge: "Legendary",
  },

  // MEN'S FRAGRANCES
  {
    id: 9,
    name: "Alsa Fragrance - Urban Legend",
    category: "men",
    price: 1,
    rating: 4.7,
    reviews: 156,
    image: "/modern-black-cologne-bottle-with-silver-alsa-fragr.jpg",
    description: "A modern masculine fragrance for the contemporary urban gentleman.",
    notes: {
      top: ["Lemon", "Grapefruit", "Mint"],
      middle: ["Lavender", "Geranium", "Cardamom"],
      base: ["Cedarwood", "Vetiver", "Ambergris"],
    },
    size: ["50ml", "100ml"],
    inStock: true,
  },
  {
    id: 10,
    name: "Alsa Fragrance - Desert Mirage",
    category: "men",
    price: 1,
    rating: 4.6,
    reviews: 178,
    image: "/bronze-desert-cologne-bottle-with-gold-alsa-fragra.jpg",
    description: "An exotic masculine scent inspired by the mystique of desert landscapes.",
    notes: {
      top: ["Cardamom", "Orange", "Cinnamon"],
      middle: ["Frankincense", "Myrrh", "Rose"],
      base: ["Oud", "Sandalwood", "Vanilla"],
    },
    size: ["50ml", "100ml"],
    inStock: true,
    badge: "Exotic",
  },
  {
    id: 11,
    name: "Alsa Fragrance - Ocean Breeze",
    category: "men",
    price: 1,
    rating: 4.8,
    reviews: 201,
    image: "/blue-ocean-cologne-bottle-with-white-alsa-fragranc.jpg",
    description: "A fresh aquatic fragrance that captures the invigorating spirit of the ocean.",
    notes: {
      top: ["Sea Salt", "Bergamot", "Aquatic Notes"],
      middle: ["Marine Accord", "Sage", "Geranium"],
      base: ["Driftwood", "Ambergris", "White Musk"],
    },
    size: ["50ml", "100ml"],
    inStock: true,
    isNew: true,
  },
  {
    id: 12,
    name: "Alsa Fragrance - Midnight Storm",
    category: "men",
    price: 1,
    rating: 4.9,
    reviews: 143,
    image: "/dark-storm-cologne-bottle-with-lightning-alsa-frag.jpg",
    description: "A powerful, intense fragrance that embodies the raw energy of a midnight storm.",
    notes: {
      top: ["Electric Ozone", "Black Pepper", "Grapefruit"],
      middle: ["Storm Accord", "Cypress", "Juniper"],
      base: ["Dark Woods", "Leather", "Smoky Amber"],
    },
    size: ["50ml", "100ml"],
    inStock: true,
    badge: "Intense",
  },
  {
    id: 13,
    name: "Alsa Fragrance - Royal Crown",
    category: "men",
    price: 1,
    rating: 4.8,
    reviews: 167,
    image: "/royal-gold-cologne-bottle-with-crown-alsa-fragranc.jpg",
    description: "A regal masculine fragrance fit for royalty, exuding power and sophistication.",
    notes: {
      top: ["Royal Saffron", "Bergamot", "Pink Pepper"],
      middle: ["Royal Rose", "Oud", "Cinnamon"],
      base: ["Royal Amber", "Sandalwood", "Musk"],
    },
    size: ["50ml", "100ml"],
    inStock: true,
    badge: "Royal",
  },
  {
    id: 14,
    name: "Alsa Fragrance - Forest King",
    category: "men",
    price: 1,
    rating: 4.6,
    reviews: 189,
    image: "/forest-green-cologne-bottle-with-tree-alsa-fragran.jpg",
    description: "A woody masculine fragrance that channels the strength and majesty of ancient forests.",
    notes: {
      top: ["Pine Needles", "Eucalyptus", "Lemon"],
      middle: ["Cedar", "Fir Balsam", "Sage"],
      base: ["Oakmoss", "Patchouli", "Amber"],
    },
    size: ["50ml", "100ml"],
    inStock: true,
  },
  {
    id: 15,
    name: "Alsa Fragrance - Steel & Fire",
    category: "men",
    price: 1,
    originalPrice: 1,
    rating: 4.7,
    reviews: 156,
    image: "/metallic-steel-cologne-bottle-with-fire-alsa-fragr.jpg",
    description: "A bold, industrial fragrance that combines metallic coolness with fiery passion.",
    notes: {
      top: ["Metallic Notes", "Red Pepper", "Ginger"],
      middle: ["Steel Accord", "Black Tea", "Cardamom"],
      base: ["Smoky Woods", "Leather", "Burnt Amber"],
    },
    size: ["50ml", "100ml"],
    inStock: true,
    isSale: true,
  },
  {
    id: 31,
    name: "Alsa Fragrance - Thunder Strike",
    category: "men",
    price: 1,
    rating: 4.7,
    reviews: 134,
    image: "/placeholder.svg?height=400&width=300",
    description: "An electrifying masculine fragrance with the power of thunder.",
    notes: {
      top: ["Electric Citrus", "Ozone", "Lightning Accord"],
      middle: ["Thunder Storm", "Metallic Notes", "Spicy Woods"],
      base: ["Storm Woods", "Electric Musk", "Charged Amber"],
    },
    size: ["50ml", "100ml"],
    inStock: true,
    badge: "Electric",
  },
  {
    id: 32,
    name: "Alsa Fragrance - Golden Eagle",
    category: "men",
    price: 1,
    rating: 4.8,
    reviews: 156,
    image: "/placeholder.svg?height=400&width=300",
    description: "A majestic fragrance that soars with the freedom and power of a golden eagle.",
    notes: {
      top: ["Golden Citrus", "Mountain Air", "Pine"],
      middle: ["Eagle Accord", "Juniper", "Sage"],
      base: ["Golden Woods", "Amber", "Soaring Musk"],
    },
    size: ["50ml", "100ml"],
    inStock: true,
    badge: "Majestic",
  },
  {
    id: 39,
    name: "Alsa Fragrance - Wolf Spirit",
    category: "men",
    price: 1,
    rating: 4.8,
    reviews: 145,
    image: "/placeholder.svg?height=400&width=300",
    description: "A wild, untamed fragrance that channels the spirit of the wolf.",
    notes: {
      top: ["Wild Herbs", "Pine", "Mountain Air"],
      middle: ["Wolf Accord", "Juniper", "Wild Sage"],
      base: ["Forest Floor", "Wild Musk", "Moonlit Woods"],
    },
    size: ["50ml", "100ml"],
    inStock: true,
    badge: "Wild",
  },

  // ATTAR COLLECTION
  {
    id: 16,
    name: "Alsa Fragrance - Royal Oud",
    category: "attars",
    price: 1,
    rating: 4.9,
    reviews: 89,
    image: "/placeholder.svg?height=400&width=300",
    description: "Premium oud attar crafted from the finest agarwood, embodying luxury and tradition.",
    notes: {
      top: ["Saffron", "Rose"],
      middle: ["Oud", "Amber"],
      base: ["Musk", "Sandalwood", "Patchouli"],
    },
    size: ["6ml", "12ml"],
    inStock: true,
    isNew: true,
    badge: "Premium",
  },
  {
    id: 17,
    name: "Alsa Fragrance - Mystic Rose",
    category: "attars",
    price: 1,
    rating: 4.8,
    reviews: 134,
    image: "/placeholder.svg?height=400&width=300",
    description: "A divine rose attar that captures the pure essence of Damascus roses.",
    notes: {
      top: ["Bulgarian Rose", "Turkish Rose"],
      middle: ["Damask Rose", "Rose Otto"],
      base: ["Rose Absolute", "Sandalwood", "Musk"],
    },
    size: ["6ml", "12ml"],
    inStock: true,
    badge: "Pure",
  },
  {
    id: 18,
    name: "Alsa Fragrance - Sacred Sandalwood",
    category: "attars",
    price: 1,
    rating: 4.7,
    reviews: 156,
    image: "/placeholder.svg?height=400&width=300",
    description: "A sacred sandalwood attar that brings peace and spiritual harmony.",
    notes: {
      top: ["Mysore Sandalwood"],
      middle: ["Australian Sandalwood", "Cardamom"],
      base: ["Sandalwood Absolute", "White Musk", "Amber"],
    },
    size: ["6ml", "12ml"],
    inStock: true,
    badge: "Sacred",
  },
  {
    id: 19,
    name: "Alsa Fragrance - Amber Nights",
    category: "attars",
    price: 1,
    rating: 4.6,
    reviews: 178,
    image: "/placeholder.svg?height=400&width=300",
    description: "A warm amber attar that evokes the mystery and allure of Arabian nights.",
    notes: {
      top: ["Saffron", "Cardamom"],
      middle: ["Amber", "Frankincense"],
      base: ["Amber Absolute", "Oud", "Musk"],
    },
    size: ["6ml", "12ml"],
    inStock: true,
  },
  {
    id: 20,
    name: "Alsa Fragrance - White Musk",
    category: "attars",
    price: 1,
    rating: 4.5,
    reviews: 201,
    image: "/placeholder.svg?height=400&width=300",
    description: "A pure white musk attar that embodies cleanliness and spiritual purity.",
    notes: {
      top: ["White Musk"],
      middle: ["Clean Musk", "Soft Florals"],
      base: ["Musk Absolute", "White Amber", "Soft Woods"],
    },
    size: ["6ml", "12ml"],
    inStock: true,
    badge: "Pure",
  },
  {
    id: 21,
    name: "Alsa Fragrance - Black Oudh Supreme",
    category: "attars",
    price: 1,
    rating: 4.9,
    reviews: 67,
    image: "/placeholder.svg?height=400&width=300",
    description: "The ultimate oud experience - rare black oud from the heart of Cambodia.",
    notes: {
      top: ["Cambodian Oud"],
      middle: ["Black Oud", "Rose"],
      base: ["Oud Absolute", "Amber", "Musk"],
    },
    size: ["3ml", "6ml", "12ml"],
    inStock: true,
    badge: "Supreme",
  },
  {
    id: 34,
    name: "Alsa Fragrance - Golden Saffron",
    category: "attars",
    price: 1,
    rating: 4.8,
    reviews: 123,
    image: "/placeholder.svg?height=400&width=300",
    description: "A precious saffron attar made from the finest Kashmir saffron.",
    notes: {
      top: ["Kashmir Saffron", "Rose"],
      middle: ["Saffron Absolute", "Cardamom"],
      base: ["Golden Amber", "Musk", "Sandalwood"],
    },
    size: ["6ml", "12ml"],
    inStock: true,
    badge: "Precious",
  },
  {
    id: 35,
    name: "Alsa Fragrance - Jasmine Nights",
    category: "attars",
    price: 1,
    rating: 4.7,
    reviews: 167,
    image: "/placeholder.svg?height=400&width=300",
    description: "A intoxicating jasmine attar that blooms in the darkness of night.",
    notes: {
      top: ["Night Jasmine", "Sambac Jasmine"],
      middle: ["Jasmine Absolute", "White Flowers"],
      base: ["Jasmine Essence", "White Musk", "Soft Woods"],
    },
    size: ["6ml", "12ml"],
    inStock: true,
    badge: "Intoxicating",
  },
  {
    id: 40,
    name: "Alsa Fragrance - Eternal Love",
    category: "attars",
    price: 1,
    rating: 4.9,
    reviews: 56,
    image: "/placeholder.svg?height=400&width=300",
    description: "A romantic attar that captures the essence of eternal, undying love.",
    notes: {
      top: ["Love Accord", "Rose", "Saffron"],
      middle: ["Heart Flowers", "Romantic Spices", "Amber"],
      base: ["Eternal Musk", "Love Potion", "Sacred Woods"],
    },
    size: ["6ml", "12ml"],
    inStock: true,
    badge: "Romantic",
  },

  // TESTER COLLECTION
  {
    id: 22,
    name: "Alsa Fragrance - Midnight Elegance Tester",
    category: "testers",
    price: 1,
    originalPrice: 1,
    rating: 4.8,
    reviews: 89,
    image: "/placeholder.svg?height=400&width=300",
    description: "Tester version of our bestselling Midnight Elegance fragrance.",
    notes: {
      top: ["Bergamot", "Black Currant", "Pink Pepper"],
      middle: ["Rose", "Jasmine", "Violet"],
      base: ["Vanilla", "Musk", "Sandalwood"],
    },
    size: ["30ml"],
    inStock: true,
    isSale: true,
    badge: "Tester",
  },
  {
    id: 23,
    name: "Alsa Fragrance - Urban Legend Tester",
    category: "testers",
    price: 1,
    originalPrice: 1,
    rating: 4.7,
    reviews: 123,
    image: "/placeholder.svg?height=400&width=300",
    description: "Tester version of our popular Urban Legend masculine fragrance.",
    notes: {
      top: ["Lemon", "Grapefruit", "Mint"],
      middle: ["Lavender", "Geranium", "Cardamom"],
      base: ["Cedarwood", "Vetiver", "Ambergris"],
    },
    size: ["30ml"],
    inStock: true,
    isSale: true,
    badge: "Tester",
  },
  {
    id: 24,
    name: "Alsa Fragrance - Royal Oud Tester",
    category: "testers",
    price: 1,
    originalPrice: 1,
    rating: 4.9,
    reviews: 67,
    image: "/placeholder.svg?height=400&width=300",
    description: "Tester version of our premium Royal Oud attar.",
    notes: {
      top: ["Saffron", "Rose"],
      middle: ["Oud", "Amber"],
      base: ["Musk", "Sandalwood", "Patchouli"],
    },
    size: ["6ml"],
    inStock: true,
    isSale: true,
    badge: "Tester",
  },
  {
    id: 25,
    name: "Alsa Fragrance - Crystal Dreams Tester",
    category: "testers",
    price: 1,
    originalPrice: 1,
    rating: 4.8,
    reviews: 78,
    image: "/placeholder.svg?height=400&width=300",
    description: "Tester version of our limited edition Crystal Dreams fragrance.",
    notes: {
      top: ["Mandarin", "Water Lily", "Freesia"],
      middle: ["Magnolia", "Lotus", "White Tea"],
      base: ["Crystal Musk", "Blonde Woods", "Soft Amber"],
    },
    size: ["30ml"],
    inStock: true,
    isSale: true,
    badge: "Tester",
  },
  {
    id: 26,
    name: "Alsa Fragrance - Ocean Breeze Tester",
    category: "testers",
    price: 1,
    originalPrice: 1,
    rating: 4.6,
    reviews: 94,
    image: "/placeholder.svg?height=400&width=300",
    description: "Tester version of our refreshing Ocean Breeze masculine fragrance.",
    notes: {
      top: ["Sea Salt", "Bergamot", "Aquatic Notes"],
      middle: ["Marine Accord", "Sage", "Geranium"],
      base: ["Driftwood", "Ambergris", "White Musk"],
    },
    size: ["30ml"],
    inStock: true,
    isSale: true,
    badge: "Tester",
  },
  {
    id: 27,
    name: "Alsa Fragrance - Rose Garden Tester",
    category: "testers",
    price: 1,
    originalPrice: 1,
    rating: 4.7,
    reviews: 112,
    image: "/placeholder.svg?height=400&width=300",
    description: "Tester version of our romantic Rose Garden fragrance.",
    notes: {
      top: ["Petitgrain", "Lemon", "Green Leaves"],
      middle: ["Rose", "Peony", "Lily of the Valley"],
      base: ["White Musk", "Cedarwood", "Amber"],
    },
    size: ["30ml"],
    inStock: true,
    isSale: true,
    badge: "Tester",
  },
  {
    id: 36,
    name: "Alsa Fragrance - Desert Mirage Tester",
    category: "testers",
    price: 1,
    originalPrice: 1,
    rating: 4.6,
    reviews: 89,
    image: "/placeholder.svg?height=400&width=300",
    description: "Tester version of our exotic Desert Mirage masculine fragrance.",
    notes: {
      top: ["Cardamom", "Orange", "Cinnamon"],
      middle: ["Frankincense", "Myrrh", "Rose"],
      base: ["Oud", "Sandalwood", "Vanilla"],
    },
    size: ["30ml"],
    inStock: true,
    isSale: true,
    badge: "Tester",
  },
  {
    id: 37,
    name: "Alsa Fragrance - Velvet Orchid Tester",
    category: "testers",
    price: 1,
    originalPrice: 1,
    rating: 4.7,
    reviews: 67,
    image: "/placeholder.svg?height=400&width=300",
    description: "Tester version of our luxurious Velvet Orchid fragrance.",
    notes: {
      top: ["Black Truffle", "Bergamot", "Honey"],
      middle: ["Black Orchid", "Lotus", "Spicy Notes"],
      base: ["Patchouli", "Vanilla", "Balsam"],
    },
    size: ["30ml"],
    inStock: true,
    isSale: true,
    badge: "Tester",
  },
]

export function getProductsByCategory(category: string) {
  return products.filter((product) => product.category === category)
}

export function getProductById(id: number) {
  return products.find((product) => product.id === id)
}

export function getFeaturedProducts() {
  return products.slice(0, 6)
}

export function searchProducts(query: string) {
  return products.filter(
    (product) =>
      product.name.toLowerCase().includes(query.toLowerCase()) ||
      product.description.toLowerCase().includes(query.toLowerCase()) ||
      product.category.toLowerCase().includes(query.toLowerCase()),
  )
}

export function getNewArrivals() {
  return products.filter((product) => product.isNew === true).slice(0, 8)
}

export function getAllNewArrivals() {
  return products.filter((product) => product.isNew === true)
}

export function getLimitedEditionProducts() {
  return products.filter((product) => product.badge === "Limited Edition")
}

export default products
