import connectDB from '../lib/mongodb'
import Product from '../lib/models/Product'

const newProducts = {
  women: [
    {
      name: "Alsa Fragrance - Enchanted Bloom",
      category: "women",
      price: 99.99,
      originalPrice: 129.99,
      salePrice: 99.99,
      salePercent: 23,
      rating: 4.8,
      reviews: 187,
      image: "/pink-rose-gold-perfume-bottle-with-alsa-fragrance-.jpg",
      images: ["/pink-rose-gold-perfume-bottle-with-alsa-fragrance-.jpg", "/floral-perfume-bottles-with-flowers-elegant.jpg"],
      description: "A magical floral fragrance that blooms with enchanting grace and feminine elegance.",
      notesTop: ["Peony", "Raspberry", "Bergamot"],
      notesMiddle: ["Garden Rose", "Jasmine", "Lilac"],
      notesBase: ["Musk", "Vanilla", "Cedarwood"],
      size: ["30ml", "50ml", "100ml"],
      inStock: true,
      isNew: true,
      isSale: true,
      badge: "New",
    },
    {
      name: "Alsa Fragrance - Celestial Grace",
      category: "women",
      price: 104.99,
      rating: 4.9,
      reviews: 223,
      image: "/crystal-clear-perfume-bottle-with-silver-alsa-frag.jpg",
      images: ["/crystal-clear-perfume-bottle-with-silver-alsa-frag.jpg"],
      description: "A heavenly fragrance that embodies divine grace and ethereal beauty.",
      notesTop: ["White Tea", "Pear", "Lemon"],
      notesMiddle: ["Magnolia", "Lotus", "Orchid"],
      notesBase: ["White Amber", "Cashmere", "Soft Musk"],
      size: ["30ml", "50ml", "100ml"],
      inStock: true,
      isNew: false,
      isSale: false,
      badge: "Premium",
    },
    {
      name: "Alsa Fragrance - Velvet Petals",
      category: "women",
      price: 97.99,
      originalPrice: 117.99,
      salePrice: 97.99,
      salePercent: 17,
      rating: 4.7,
      reviews: 165,
      image: "/elegant-black-perfume-bottle-with-gold-alsa-fragra.jpg",
      images: ["/elegant-black-perfume-bottle-with-gold-alsa-fragra.jpg"],
      description: "A luxurious floral fragrance with velvety softness and rich depth.",
      notesTop: ["Black Currant", "Pink Pepper", "Mandarin"],
      notesMiddle: ["Velvet Rose", "Peony", "Violet"],
      notesBase: ["Patchouli", "Amber", "Musk"],
      size: ["30ml", "50ml", "100ml"],
      inStock: true,
      isNew: false,
      isSale: true,
      badge: "Sale",
    },
    {
      name: "Alsa Fragrance - Tropical Paradise",
      category: "women",
      price: 89.99,
      rating: 4.6,
      reviews: 198,
      image: "/golden-amber-perfume-bottle-with-alsa-fragrance-lo.jpg",
      images: ["/golden-amber-perfume-bottle-with-alsa-fragrance-lo.jpg"],
      description: "An exotic tropical fragrance that transports you to a sun-kissed paradise.",
      notesTop: ["Coconut", "Mango", "Passionfruit"],
      notesMiddle: ["Tuberose", "Frangipani", "Ylang-Ylang"],
      notesBase: ["Vanilla", "Sandalwood", "Amber"],
      size: ["30ml", "50ml", "100ml"],
      inStock: true,
      isNew: true,
      isSale: false,
      badge: "New",
    },
    {
      name: "Alsa Fragrance - Mystic Moonlight",
      category: "women",
      price: 102.99,
      rating: 4.8,
      reviews: 176,
      image: "/silver-moonlight-perfume-bottle-with-alsa-fragranc.jpg",
      images: ["/silver-moonlight-perfume-bottle-with-alsa-fragranc.jpg"],
      description: "A mysterious nocturnal fragrance that captures the magic of moonlit nights.",
      notesTop: ["Night Jasmine", "Silver Berry", "Dewdrops"],
      notesMiddle: ["Moonflower", "White Rose", "Iris"],
      notesBase: ["White Musk", "Cashmere Wood", "Soft Vanilla"],
      size: ["30ml", "50ml", "100ml"],
      inStock: true,
      isNew: false,
      isSale: false,
      badge: "Mystic",
    },
    {
      name: "Alsa Fragrance - Spring Awakening",
      category: "women",
      price: 86.99,
      originalPrice: 106.99,
      salePrice: 86.99,
      salePercent: 19,
      rating: 4.5,
      reviews: 142,
      image: "/pink-cherry-blossom-perfume-bottle-with-alsa-fragr.jpg",
      images: ["/pink-cherry-blossom-perfume-bottle-with-alsa-fragr.jpg"],
      description: "A fresh spring fragrance that celebrates the awakening of nature.",
      notesTop: ["Cherry Blossom", "Lemon", "Green Leaves"],
      notesMiddle: ["Sakura", "Peony", "Lily"],
      notesBase: ["Soft Musk", "Cedar", "Light Amber"],
      size: ["30ml", "50ml", "100ml"],
      inStock: true,
      isNew: false,
      isSale: true,
      badge: "Sale",
    },
    {
      name: "Alsa Fragrance - Royal Essence",
      category: "women",
      price: 108.99,
      rating: 4.9,
      reviews: 201,
      image: "/deep-purple-velvet-perfume-bottle-with-gold-alsa-f.jpg",
      images: ["/deep-purple-velvet-perfume-bottle-with-gold-alsa-f.jpg"],
      description: "A regal fragrance fit for royalty, with opulent notes of luxury and elegance.",
      notesTop: ["Black Truffle", "Bergamot", "Honey"],
      notesMiddle: ["Black Orchid", "Lotus", "Spicy Notes"],
      notesBase: ["Patchouli", "Vanilla", "Balsam"],
      size: ["30ml", "50ml", "100ml"],
      inStock: true,
      isNew: true,
      isSale: false,
      badge: "Royal",
    },
    {
      name: "Alsa Fragrance - Ocean Mist",
      category: "women",
      price: 91.99,
      rating: 4.7,
      reviews: 154,
      image: "/blue-ocean-cologne-bottle-with-white-alsa-fragranc.jpg",
      images: ["/blue-ocean-cologne-bottle-with-white-alsa-fragranc.jpg"],
      description: "A refreshing aquatic fragrance that captures the essence of ocean mist.",
      notesTop: ["Sea Salt", "Bergamot", "Aquatic Notes"],
      notesMiddle: ["Marine Accord", "Sage", "Geranium"],
      notesBase: ["Driftwood", "Ambergris", "White Musk"],
      size: ["30ml", "50ml", "100ml"],
      inStock: true,
      isNew: false,
      isSale: false,
      badge: null,
    },
    {
      name: "Alsa Fragrance - Honeyed Dreams",
      category: "women",
      price: 94.99,
      originalPrice: 114.99,
      salePrice: 94.99,
      salePercent: 17,
      rating: 4.6,
      reviews: 189,
      image: "/sandalwood-vanilla-amber-warm-ingredients-perfume-.jpg",
      images: ["/sandalwood-vanilla-amber-warm-ingredients-perfume-.jpg"],
      description: "A sweet, dreamy fragrance with warm honeyed notes that wrap you in comfort.",
      notesTop: ["Honey", "Caramel", "Almond"],
      notesMiddle: ["Vanilla", "Tonka Bean", "Cream"],
      notesBase: ["Amber", "Sandalwood", "Musk"],
      size: ["30ml", "50ml", "100ml"],
      inStock: true,
      isNew: false,
      isSale: true,
      badge: "Sale",
    },
    {
      name: "Alsa Fragrance - Gardenia Nights",
      category: "women",
      price: 101.99,
      rating: 4.8,
      reviews: 167,
      image: "/emerald-green-perfume-bottle-with-gold-alsa-fragra.jpg",
      images: ["/emerald-green-perfume-bottle-with-gold-alsa-fragra.jpg"],
      description: "An intoxicating white floral fragrance that blooms in the evening air.",
      notesTop: ["Gardenia", "Orange Blossom", "Bergamot"],
      notesMiddle: ["Gardenia Absolute", "Tuberose", "Jasmine"],
      notesBase: ["White Musk", "Sandalwood", "Amber"],
      size: ["30ml", "50ml", "100ml"],
      inStock: true,
      isNew: true,
      isSale: false,
      badge: "New",
    },
  ],
  men: [
    {
      name: "Alsa Fragrance - Arctic Storm",
      category: "men",
      price: 95.99,
      rating: 4.8,
      reviews: 178,
      image: "/powerful-titanium-cologne-bottle-with-alsa-fragran.jpg",
      images: ["/powerful-titanium-cologne-bottle-with-alsa-fragran.jpg"],
      description: "A cool, powerful fragrance that embodies the raw force of an arctic storm.",
      notesTop: ["Icy Mint", "Grapefruit", "Black Pepper"],
      notesMiddle: ["Arctic Accord", "Cedar", "Vetiver"],
      notesBase: ["Leather", "Amber", "Musk"],
      size: ["50ml", "100ml"],
      inStock: true,
      isNew: true,
      isSale: false,
      badge: "New",
    },
    {
      name: "Alsa Fragrance - Noble Heritage",
      category: "men",
      price: 107.99,
      rating: 4.9,
      reviews: 212,
      image: "/royal-gold-cologne-bottle-with-crown-alsa-fragranc.jpg",
      images: ["/royal-gold-cologne-bottle-with-crown-alsa-fragranc.jpg"],
      description: "A distinguished fragrance that honors a legacy of nobility and excellence.",
      notesTop: ["Royal Saffron", "Bergamot", "Pink Pepper"],
      notesMiddle: ["Royal Rose", "Oud", "Cinnamon"],
      notesBase: ["Royal Amber", "Sandalwood", "Musk"],
      size: ["50ml", "100ml"],
      inStock: true,
      isNew: false,
      isSale: false,
      badge: "Heritage",
    },
    {
      name: "Alsa Fragrance - Coastal Breeze",
      category: "men",
      price: 88.99,
      originalPrice: 108.99,
      salePrice: 88.99,
      salePercent: 18,
      rating: 4.7,
      reviews: 165,
      image: "/blue-ocean-cologne-bottle-with-white-alsa-fragranc.jpg",
      images: ["/blue-ocean-cologne-bottle-with-white-alsa-fragranc.jpg"],
      description: "A refreshing coastal fragrance that captures the invigorating sea breeze.",
      notesTop: ["Sea Salt", "Bergamot", "Aquatic Notes"],
      notesMiddle: ["Marine Accord", "Sage", "Geranium"],
      notesBase: ["Driftwood", "Ambergris", "White Musk"],
      size: ["50ml", "100ml"],
      inStock: true,
      isNew: false,
      isSale: true,
      badge: "Sale",
    },
    {
      name: "Alsa Fragrance - Timber Wolf",
      category: "men",
      price: 96.99,
      rating: 4.8,
      reviews: 189,
      image: "/forest-green-cologne-bottle-with-tree-alsa-fragran.jpg",
      images: ["/forest-green-cologne-bottle-with-tree-alsa-fragran.jpg"],
      description: "A rugged woodland fragrance that channels the spirit of the wild timber wolf.",
      notesTop: ["Pine", "Eucalyptus", "Lemon"],
      notesMiddle: ["Cedar", "Fir", "Sage"],
      notesBase: ["Oakmoss", "Patchouli", "Amber"],
      size: ["50ml", "100ml"],
      inStock: true,
      isNew: true,
      isSale: false,
      badge: "Wild",
    },
    {
      name: "Alsa Fragrance - Midnight Racer",
      category: "men",
      price: 99.99,
      rating: 4.7,
      reviews: 156,
      image: "/dark-storm-cologne-bottle-with-lightning-alsa-frag.jpg",
      images: ["/dark-storm-cologne-bottle-with-lightning-alsa-frag.jpg"],
      description: "A high-octane fragrance for the man who lives life in the fast lane.",
      notesTop: ["Black Pepper", "Grapefruit", "Ozone"],
      notesMiddle: ["Storm Accord", "Cypress", "Juniper"],
      notesBase: ["Dark Woods", "Leather", "Smoky Amber"],
      size: ["50ml", "100ml"],
      inStock: true,
      isNew: false,
      isSale: false,
      badge: "Intense",
    },
    {
      name: "Alsa Fragrance - Bronze Warrior",
      category: "men",
      price: 93.99,
      originalPrice: 113.99,
      salePrice: 93.99,
      salePercent: 18,
      rating: 4.6,
      reviews: 174,
      image: "/bronze-desert-cologne-bottle-with-gold-alsa-fragra.jpg",
      images: ["/bronze-desert-cologne-bottle-with-gold-alsa-fragra.jpg"],
      description: "A bold desert-inspired fragrance for the warrior who conquers all challenges.",
      notesTop: ["Cardamom", "Orange", "Cinnamon"],
      notesMiddle: ["Frankincense", "Myrrh", "Rose"],
      notesBase: ["Oud", "Sandalwood", "Vanilla"],
      size: ["50ml", "100ml"],
      inStock: true,
      isNew: false,
      isSale: true,
      badge: "Sale",
    },
    {
      name: "Alsa Fragrance - Platinum Edge",
      category: "men",
      price: 104.99,
      rating: 4.8,
      reviews: 198,
      image: "/platinum-silver-cologne-bottle-with-alsa-fragrance.jpg",
      images: ["/platinum-silver-cologne-bottle-with-alsa-fragrance.jpg"],
      description: "A sharp, modern fragrance with the cutting edge of platinum sophistication.",
      notesTop: ["Bergamot", "Lemon", "Mint"],
      notesMiddle: ["Platinum Accord", "Lavender", "Geranium"],
      notesBase: ["Sandalwood", "Amber", "Musk"],
      size: ["50ml", "100ml"],
      inStock: true,
      isNew: true,
      isSale: false,
      badge: "Premium",
    },
    {
      name: "Alsa Fragrance - Urban Commander",
      category: "men",
      price: 91.99,
      rating: 4.7,
      reviews: 143,
      image: "/modern-black-cologne-bottle-with-silver-alsa-fragr.jpg",
      images: ["/modern-black-cologne-bottle-with-silver-alsa-fragr.jpg"],
      description: "A commanding urban fragrance for the modern leader who takes charge.",
      notesTop: ["Lemon", "Grapefruit", "Mint"],
      notesMiddle: ["Lavender", "Geranium", "Cardamom"],
      notesBase: ["Cedarwood", "Vetiver", "Ambergris"],
      size: ["50ml", "100ml"],
      inStock: true,
      isNew: false,
      isSale: false,
      badge: null,
    },
    {
      name: "Alsa Fragrance - Fire Forged",
      category: "men",
      price: 98.99,
      originalPrice: 118.99,
      salePrice: 98.99,
      salePercent: 17,
      rating: 4.7,
      reviews: 167,
      image: "/metallic-steel-cologne-bottle-with-fire-alsa-fragr.jpg",
      images: ["/metallic-steel-cologne-bottle-with-fire-alsa-fragr.jpg"],
      description: "A powerful industrial fragrance forged in fire, combining strength with passion.",
      notesTop: ["Metallic Notes", "Red Pepper", "Ginger"],
      notesMiddle: ["Steel Accord", "Black Tea", "Cardamom"],
      notesBase: ["Smoky Woods", "Leather", "Burnt Amber"],
      size: ["50ml", "100ml"],
      inStock: true,
      isNew: false,
      isSale: true,
      badge: "Sale",
    },
    {
      name: "Alsa Fragrance - Sapphire Elite",
      category: "men",
      price: 106.99,
      rating: 4.9,
      reviews: 234,
      image: "/luxury-blue-sapphire-perfume-bottle-with-alsa-frag.jpg",
      images: ["/luxury-blue-sapphire-perfume-bottle-with-alsa-frag.jpg"],
      description: "An elite aquatic fragrance as deep and precious as a sapphire gemstone.",
      notesTop: ["Sea Salt", "Bergamot", "Aquatic Notes"],
      notesMiddle: ["Marine Accord", "Sage", "Geranium"],
      notesBase: ["Driftwood", "Ambergris", "White Musk"],
      size: ["50ml", "100ml"],
      inStock: true,
      isNew: true,
      isSale: false,
      badge: "Elite",
    },
  ],
  attars: [
    {
      name: "Alsa Fragrance - Imperial Oud",
      category: "attars",
      price: 159.99,
      rating: 4.9,
      reviews: 95,
      image: "/royal-oud-perfume-bottles-luxury-gold.jpg",
      images: ["/royal-oud-perfume-bottles-luxury-gold.jpg"],
      description: "An imperial oud attar crafted from the rarest agarwood, fit for royalty.",
      notesTop: ["Saffron", "Rose"],
      notesMiddle: ["Oud", "Amber"],
      notesBase: ["Musk", "Sandalwood", "Patchouli"],
      size: ["6ml", "12ml"],
      inStock: true,
      isNew: true,
      isSale: false,
      badge: "Imperial",
    },
    {
      name: "Alsa Fragrance - Divine Rose",
      category: "attars",
      price: 139.99,
      rating: 4.8,
      reviews: 147,
      image: "/rose-jasmine-flowers-perfume-heart-notes-floral-bo.jpg",
      images: ["/rose-jasmine-flowers-perfume-heart-notes-floral-bo.jpg"],
      description: "A divine rose attar that captures the pure essence of the finest roses.",
      notesTop: ["Bulgarian Rose", "Turkish Rose"],
      notesMiddle: ["Damask Rose", "Rose Otto"],
      notesBase: ["Rose Absolute", "Sandalwood", "Musk"],
      size: ["6ml", "12ml"],
      inStock: true,
      isNew: false,
      isSale: false,
      badge: "Divine",
    },
    {
      name: "Alsa Fragrance - Sacred Woods",
      category: "attars",
      price: 129.99,
      rating: 4.7,
      reviews: 168,
      image: "/sandalwood-vanilla-amber-warm-ingredients-perfume-.jpg",
      images: ["/sandalwood-vanilla-amber-warm-ingredients-perfume-.jpg"],
      description: "A sacred sandalwood attar that brings spiritual harmony and inner peace.",
      notesTop: ["Mysore Sandalwood"],
      notesMiddle: ["Australian Sandalwood", "Cardamom"],
      notesBase: ["Sandalwood Absolute", "White Musk", "Amber"],
      size: ["6ml", "12ml"],
      inStock: true,
      isNew: false,
      isSale: false,
      badge: "Sacred",
    },
    {
      name: "Alsa Fragrance - Golden Amber",
      category: "attars",
      price: 134.99,
      originalPrice: 164.99,
      salePrice: 134.99,
      salePercent: 18,
      rating: 4.6,
      reviews: 192,
      image: "/golden-amber-perfume-bottle-with-alsa-fragrance-lo.jpg",
      images: ["/golden-amber-perfume-bottle-with-alsa-fragrance-lo.jpg"],
      description: "A warm golden amber attar that evokes the mystery of ancient treasures.",
      notesTop: ["Saffron", "Cardamom"],
      notesMiddle: ["Amber", "Frankincense"],
      notesBase: ["Amber Absolute", "Oud", "Musk"],
      size: ["6ml", "12ml"],
      inStock: true,
      isNew: false,
      isSale: true,
      badge: "Sale",
    },
    {
      name: "Alsa Fragrance - Pure White",
      category: "attars",
      price: 119.99,
      rating: 4.5,
      reviews: 215,
      image: "/crystal-clear-perfume-bottle-with-silver-alsa-frag.jpg",
      images: ["/crystal-clear-perfume-bottle-with-silver-alsa-frag.jpg"],
      description: "A pure white musk attar that embodies cleanliness and spiritual purity.",
      notesTop: ["White Musk"],
      notesMiddle: ["Clean Musk", "Soft Florals"],
      notesBase: ["Musk Absolute", "White Amber", "Soft Woods"],
      size: ["6ml", "12ml"],
      inStock: true,
      isNew: true,
      isSale: false,
      badge: "Pure",
    },
    {
      name: "Alsa Fragrance - Black Diamond Oud",
      category: "attars",
      price: 189.99,
      rating: 4.9,
      reviews: 78,
      image: "/royal-oud-perfume-bottles-luxury-gold.jpg",
      images: ["/royal-oud-perfume-bottles-luxury-gold.jpg"],
      description: "The ultimate oud experience - rare black diamond oud from Cambodia's heart.",
      notesTop: ["Cambodian Oud"],
      notesMiddle: ["Black Oud", "Rose"],
      notesBase: ["Oud Absolute", "Amber", "Musk"],
      size: ["3ml", "6ml", "12ml"],
      inStock: true,
      isNew: false,
      isSale: false,
      badge: "Diamond",
    },
    {
      name: "Alsa Fragrance - Saffron Gold",
      category: "attars",
      price: 149.99,
      rating: 4.8,
      reviews: 135,
      image: "/golden-amber-perfume-bottle-with-alsa-fragrance-lo.jpg",
      images: ["/golden-amber-perfume-bottle-with-alsa-fragrance-lo.jpg"],
      description: "A precious saffron attar made from the finest Kashmir saffron threads.",
      notesTop: ["Kashmir Saffron", "Rose"],
      notesMiddle: ["Saffron Absolute", "Cardamom"],
      notesBase: ["Golden Amber", "Musk", "Sandalwood"],
      size: ["6ml", "12ml"],
      inStock: true,
      isNew: true,
      isSale: false,
      badge: "Precious",
    },
    {
      name: "Alsa Fragrance - Night Jasmine",
      category: "attars",
      price: 144.99,
      rating: 4.7,
      reviews: 179,
      image: "/rose-jasmine-flowers-perfume-heart-notes-floral-bo.jpg",
      images: ["/rose-jasmine-flowers-perfume-heart-notes-floral-bo.jpg"],
      description: "An intoxicating jasmine attar that blooms in the darkness of night.",
      notesTop: ["Night Jasmine", "Sambac Jasmine"],
      notesMiddle: ["Jasmine Absolute", "White Flowers"],
      notesBase: ["Jasmine Essence", "White Musk", "Soft Woods"],
      size: ["6ml", "12ml"],
      inStock: true,
      isNew: false,
      isSale: false,
      badge: "Intoxicating",
    },
    {
      name: "Alsa Fragrance - Eternal Bond",
      category: "attars",
      price: 169.99,
      originalPrice: 199.99,
      salePrice: 169.99,
      salePercent: 15,
      rating: 4.9,
      reviews: 67,
      image: "/pink-rose-gold-perfume-bottle-with-alsa-fragrance-.jpg",
      images: ["/pink-rose-gold-perfume-bottle-with-alsa-fragrance-.jpg"],
      description: "A romantic attar that captures the essence of eternal, unbreakable bonds.",
      notesTop: ["Love Accord", "Rose", "Saffron"],
      notesMiddle: ["Heart Flowers", "Romantic Spices", "Amber"],
      notesBase: ["Eternal Musk", "Love Potion", "Sacred Woods"],
      size: ["6ml", "12ml"],
      inStock: true,
      isNew: false,
      isSale: true,
      badge: "Romantic",
    },
    {
      name: "Alsa Fragrance - Mystic Oudh",
      category: "attars",
      price: 179.99,
      rating: 4.8,
      reviews: 112,
      image: "/royal-oud-perfume-bottles-luxury-gold.jpg",
      images: ["/royal-oud-perfume-bottles-luxury-gold.jpg"],
      description: "A mystical oud attar with deep, complex notes that transport you to ancient times.",
      notesTop: ["Saffron", "Rose", "Cardamom"],
      notesMiddle: ["Mystic Oud", "Amber", "Frankincense"],
      notesBase: ["Oud Absolute", "Musk", "Sandalwood"],
      size: ["6ml", "12ml"],
      inStock: true,
      isNew: true,
      isSale: false,
      badge: "Mystic",
    },
  ],
  testers: [
    {
      name: "Alsa Fragrance - Enchanted Bloom Tester",
      category: "testers",
      price: 32.99,
      originalPrice: 42.99,
      salePrice: 32.99,
      salePercent: 23,
      rating: 4.8,
      reviews: 95,
      image: "/pink-rose-gold-perfume-bottle-with-alsa-fragrance-.jpg",
      images: ["/pink-rose-gold-perfume-bottle-with-alsa-fragrance-.jpg"],
      description: "Tester version of our magical Enchanted Bloom fragrance.",
      notesTop: ["Peony", "Raspberry", "Bergamot"],
      notesMiddle: ["Garden Rose", "Jasmine", "Lilac"],
      notesBase: ["Musk", "Vanilla", "Cedarwood"],
      size: ["30ml"],
      inStock: true,
      isNew: false,
      isSale: true,
      badge: "Tester",
    },
    {
      name: "Alsa Fragrance - Arctic Storm Tester",
      category: "testers",
      price: 35.99,
      originalPrice: 45.99,
      salePrice: 35.99,
      salePercent: 22,
      rating: 4.8,
      reviews: 112,
      image: "/powerful-titanium-cologne-bottle-with-alsa-fragran.jpg",
      images: ["/powerful-titanium-cologne-bottle-with-alsa-fragran.jpg"],
      description: "Tester version of our powerful Arctic Storm masculine fragrance.",
      notesTop: ["Icy Mint", "Grapefruit", "Black Pepper"],
      notesMiddle: ["Arctic Accord", "Cedar", "Vetiver"],
      notesBase: ["Leather", "Amber", "Musk"],
      size: ["30ml"],
      inStock: true,
      isNew: false,
      isSale: true,
      badge: "Tester",
    },
    {
      name: "Alsa Fragrance - Imperial Oud Tester",
      category: "testers",
      price: 54.99,
      originalPrice: 64.99,
      salePrice: 54.99,
      salePercent: 15,
      rating: 4.9,
      reviews: 78,
      image: "/royal-oud-perfume-bottles-luxury-gold.jpg",
      images: ["/royal-oud-perfume-bottles-luxury-gold.jpg"],
      description: "Tester version of our premium Imperial Oud attar.",
      notesTop: ["Saffron", "Rose"],
      notesMiddle: ["Oud", "Amber"],
      notesBase: ["Musk", "Sandalwood", "Patchouli"],
      size: ["6ml"],
      inStock: true,
      isNew: false,
      isSale: true,
      badge: "Tester",
    },
    {
      name: "Alsa Fragrance - Celestial Grace Tester",
      category: "testers",
      price: 37.99,
      originalPrice: 47.99,
      salePrice: 37.99,
      salePercent: 21,
      rating: 4.9,
      reviews: 89,
      image: "/crystal-clear-perfume-bottle-with-silver-alsa-frag.jpg",
      images: ["/crystal-clear-perfume-bottle-with-silver-alsa-frag.jpg"],
      description: "Tester version of our heavenly Celestial Grace fragrance.",
      notesTop: ["White Tea", "Pear", "Lemon"],
      notesMiddle: ["Magnolia", "Lotus", "Orchid"],
      notesBase: ["White Amber", "Cashmere", "Soft Musk"],
      size: ["30ml"],
      inStock: true,
      isNew: false,
      isSale: true,
      badge: "Tester",
    },
    {
      name: "Alsa Fragrance - Coastal Breeze Tester",
      category: "testers",
      price: 33.99,
      originalPrice: 43.99,
      salePrice: 33.99,
      salePercent: 23,
      rating: 4.7,
      reviews: 101,
      image: "/blue-ocean-cologne-bottle-with-white-alsa-fragranc.jpg",
      images: ["/blue-ocean-cologne-bottle-with-white-alsa-fragranc.jpg"],
      description: "Tester version of our refreshing Coastal Breeze masculine fragrance.",
      notesTop: ["Sea Salt", "Bergamot", "Aquatic Notes"],
      notesMiddle: ["Marine Accord", "Sage", "Geranium"],
      notesBase: ["Driftwood", "Ambergris", "White Musk"],
      size: ["30ml"],
      inStock: true,
      isNew: false,
      isSale: true,
      badge: "Tester",
    },
    {
      name: "Alsa Fragrance - Velvet Petals Tester",
      category: "testers",
      price: 36.99,
      originalPrice: 46.99,
      salePrice: 36.99,
      salePercent: 21,
      rating: 4.7,
      reviews: 87,
      image: "/elegant-black-perfume-bottle-with-gold-alsa-fragra.jpg",
      images: ["/elegant-black-perfume-bottle-with-gold-alsa-fragra.jpg"],
      description: "Tester version of our luxurious Velvet Petals fragrance.",
      notesTop: ["Black Currant", "Pink Pepper", "Mandarin"],
      notesMiddle: ["Velvet Rose", "Peony", "Violet"],
      notesBase: ["Patchouli", "Amber", "Musk"],
      size: ["30ml"],
      inStock: true,
      isNew: false,
      isSale: true,
      badge: "Tester",
    },
    {
      name: "Alsa Fragrance - Timber Wolf Tester",
      category: "testers",
      price: 35.99,
      originalPrice: 45.99,
      salePrice: 35.99,
      salePercent: 22,
      rating: 4.8,
      reviews: 124,
      image: "/forest-green-cologne-bottle-with-tree-alsa-fragran.jpg",
      images: ["/forest-green-cologne-bottle-with-tree-alsa-fragran.jpg"],
      description: "Tester version of our rugged Timber Wolf masculine fragrance.",
      notesTop: ["Pine", "Eucalyptus", "Lemon"],
      notesMiddle: ["Cedar", "Fir", "Sage"],
      notesBase: ["Oakmoss", "Patchouli", "Amber"],
      size: ["30ml"],
      inStock: true,
      isNew: false,
      isSale: true,
      badge: "Tester",
    },
    {
      name: "Alsa Fragrance - Mystic Moonlight Tester",
      category: "testers",
      price: 38.99,
      originalPrice: 48.99,
      salePrice: 38.99,
      salePercent: 20,
      rating: 4.8,
      reviews: 76,
      image: "/silver-moonlight-perfume-bottle-with-alsa-fragranc.jpg",
      images: ["/silver-moonlight-perfume-bottle-with-alsa-fragranc.jpg"],
      description: "Tester version of our mysterious Mystic Moonlight fragrance.",
      notesTop: ["Night Jasmine", "Silver Berry", "Dewdrops"],
      notesMiddle: ["Moonflower", "White Rose", "Iris"],
      notesBase: ["White Musk", "Cashmere Wood", "Soft Vanilla"],
      size: ["30ml"],
      inStock: true,
      isNew: false,
      isSale: true,
      badge: "Tester",
    },
    {
      name: "Alsa Fragrance - Midnight Racer Tester",
      category: "testers",
      price: 36.99,
      originalPrice: 46.99,
      salePrice: 36.99,
      salePercent: 21,
      rating: 4.7,
      reviews: 98,
      image: "/dark-storm-cologne-bottle-with-lightning-alsa-frag.jpg",
      images: ["/dark-storm-cologne-bottle-with-lightning-alsa-frag.jpg"],
      description: "Tester version of our intense Midnight Racer masculine fragrance.",
      notesTop: ["Black Pepper", "Grapefruit", "Ozone"],
      notesMiddle: ["Storm Accord", "Cypress", "Juniper"],
      notesBase: ["Dark Woods", "Leather", "Smoky Amber"],
      size: ["30ml"],
      inStock: true,
      isNew: false,
      isSale: true,
      badge: "Tester",
    },
    {
      name: "Alsa Fragrance - Noble Heritage Tester",
      category: "testers",
      price: 39.99,
      originalPrice: 49.99,
      salePrice: 39.99,
      salePercent: 20,
      rating: 4.9,
      reviews: 156,
      image: "/royal-gold-cologne-bottle-with-crown-alsa-fragranc.jpg",
      images: ["/royal-gold-cologne-bottle-with-crown-alsa-fragranc.jpg"],
      description: "Tester version of our distinguished Noble Heritage masculine fragrance.",
      notesTop: ["Royal Saffron", "Bergamot", "Pink Pepper"],
      notesMiddle: ["Royal Rose", "Oud", "Cinnamon"],
      notesBase: ["Royal Amber", "Sandalwood", "Musk"],
      size: ["30ml"],
      inStock: true,
      isNew: false,
      isSale: true,
      badge: "Tester",
    },
  ],
}

async function main() {
  console.log('Starting to add 10 unique products per category to MongoDB Atlas...\n')

  // Connect to MongoDB
  await connectDB()
  console.log('✅ Connected to MongoDB Atlas\n')

  let totalImported = 0
  let totalFailed = 0

  // Add products for each category
  for (const [category, products] of Object.entries(newProducts)) {
    console.log(`\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`)
    console.log(`Adding ${products.length} products for category: ${category.toUpperCase()}`)
    console.log(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`)

    let categoryImported = 0
    let categoryFailed = 0

    for (const product of products) {
      try {
        await Product.create(product)
        categoryImported++
        totalImported++
        console.log(`[${categoryImported}/${products.length}] ✅ Imported: ${product.name}`)
      } catch (error: any) {
        categoryFailed++
        totalFailed++
        console.error(`❌ Error importing ${product.name}:`, error.message)
      }
    }

    console.log(`\nCategory ${category.toUpperCase()} Summary:`)
    console.log(`  - Successfully imported: ${categoryImported}`)
    console.log(`  - Failed: ${categoryFailed}`)
  }

  const totalInDb = await Product.countDocuments()
  const byCategory = {
    women: await Product.countDocuments({ category: 'women' }),
    men: await Product.countDocuments({ category: 'men' }),
    attars: await Product.countDocuments({ category: 'attars' }),
    testers: await Product.countDocuments({ category: 'testers' }),
  }

  console.log(`\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`)
  console.log(`✨ Product import completed!`)
  console.log(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`)
  console.log(`Total Summary:`)
  console.log(`  - Successfully imported: ${totalImported}`)
  console.log(`  - Failed: ${totalFailed}`)
  console.log(`  - Total products in database: ${totalInDb}`)
  console.log(`\nProducts by Category:`)
  console.log(`  - Women: ${byCategory.women}`)
  console.log(`  - Men: ${byCategory.men}`)
  console.log(`  - Attars: ${byCategory.attars}`)
  console.log(`  - Testers: ${byCategory.testers}`)
  console.log(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`)
}

main()
  .catch((e) => {
    console.error('Fatal error:', e)
    process.exit(1)
  })
  .finally(() => {
    process.exit(0)
  })

