import connectDB from '../lib/mongodb'
import Product from '../lib/models/Product'

const newProducts = {
  women: [
    {
      name: "Alsa Fragrance - Blossom Dreams",
      category: "women",
      price: 89.99,
      originalPrice: 119.99,
      salePrice: 89.99,
      salePercent: 25,
      rating: 4.7,
      reviews: 156,
      image: "/pink-rose-gold-perfume-bottle-with-alsa-fragrance-.jpg",
      images: ["/pink-rose-gold-perfume-bottle-with-alsa-fragrance-.jpg", "/floral-perfume-bottles-with-flowers-elegant.jpg"],
      description: "A delicate floral fragrance that captures the essence of spring blossoms and morning dew.",
      notesTop: ["Peach", "Apricot", "Bergamot"],
      notesMiddle: ["Rose", "Jasmine", "Lily"],
      notesBase: ["Musk", "Vanilla", "Sandalwood"],
      size: ["30ml", "50ml", "100ml"],
      inStock: true,
      isNew: true,
      isSale: true,
      badge: "New",
    },
    {
      name: "Alsa Fragrance - Velvet Rose",
      category: "women",
      price: 95.99,
      rating: 4.8,
      reviews: 203,
      image: "/elegant-black-perfume-bottle-with-gold-alsa-fragra.jpg",
      images: ["/elegant-black-perfume-bottle-with-gold-alsa-fragra.jpg"],
      description: "A luxurious rose fragrance with velvety undertones that exudes elegance and sophistication.",
      notesTop: ["Black Currant", "Pink Pepper", "Bergamot"],
      notesMiddle: ["Damask Rose", "Peony", "Violet"],
      notesBase: ["Patchouli", "Amber", "Musk"],
      size: ["30ml", "50ml", "100ml"],
      inStock: true,
      isNew: false,
      isSale: false,
      badge: "Premium",
    },
    {
      name: "Alsa Fragrance - Sunset Glow",
      category: "women",
      price: 79.99,
      originalPrice: 99.99,
      salePrice: 79.99,
      salePercent: 20,
      rating: 4.6,
      reviews: 178,
      image: "/golden-amber-perfume-bottle-with-alsa-fragrance-lo.jpg",
      images: ["/golden-amber-perfume-bottle-with-alsa-fragrance-lo.jpg"],
      description: "A warm, radiant fragrance that captures the golden hour's magical warmth and beauty.",
      notesTop: ["Orange Blossom", "Mandarin", "Ginger"],
      notesMiddle: ["Tuberose", "Ylang-Ylang", "Coconut"],
      notesBase: ["Amber", "Sandalwood", "Tonka Bean"],
      size: ["30ml", "50ml", "100ml"],
      inStock: true,
      isNew: false,
      isSale: true,
      badge: "Sale",
    },
    {
      name: "Alsa Fragrance - Mystic Garden",
      category: "women",
      price: 92.99,
      rating: 4.9,
      reviews: 234,
      image: "/emerald-green-perfume-bottle-with-gold-alsa-fragra.jpg",
      images: ["/emerald-green-perfume-bottle-with-gold-alsa-fragra.jpg"],
      description: "An enchanting green fragrance that transports you to a secret garden filled with exotic blooms.",
      notesTop: ["Green Mandarin", "Basil", "Mint"],
      notesMiddle: ["Green Tea", "Bamboo", "Lily of the Valley"],
      notesBase: ["Vetiver", "White Cedar", "Green Musk"],
      size: ["30ml", "50ml", "100ml"],
      inStock: true,
      isNew: true,
      isSale: false,
      badge: "New",
    },
    {
      name: "Alsa Fragrance - Pearl Essence",
      category: "women",
      price: 88.99,
      rating: 4.7,
      reviews: 167,
      image: "/crystal-clear-perfume-bottle-with-silver-alsa-frag.jpg",
      images: ["/crystal-clear-perfume-bottle-with-silver-alsa-frag.jpg"],
      description: "A luminous white floral fragrance that sparkles with crystalline freshness and purity.",
      notesTop: ["Pear", "Freesia", "Water Lily"],
      notesMiddle: ["Magnolia", "Lotus", "White Tea"],
      notesBase: ["Crystal Musk", "Blonde Woods", "Soft Amber"],
      size: ["30ml", "50ml", "100ml"],
      inStock: true,
      isNew: false,
      isSale: false,
      badge: null,
    },
    {
      name: "Alsa Fragrance - Enchanted Forest",
      category: "women",
      price: 94.99,
      rating: 4.8,
      reviews: 189,
      image: "/forest-green-cologne-bottle-with-tree-alsa-fragran.jpg",
      images: ["/forest-green-cologne-bottle-with-tree-alsa-fragran.jpg"],
      description: "A mystical woodland fragrance that captures the magic of an enchanted forest.",
      notesTop: ["Pine Needles", "Eucalyptus", "Lemon"],
      notesMiddle: ["Cedar", "Fir Balsam", "Sage"],
      notesBase: ["Oakmoss", "Patchouli", "Amber"],
      size: ["30ml", "50ml", "100ml"],
      inStock: true,
      isNew: true,
      isSale: false,
      badge: "New",
    },
    {
      name: "Alsa Fragrance - Royal Jasmine",
      category: "women",
      price: 97.99,
      rating: 4.9,
      reviews: 145,
      image: "/rose-jasmine-flowers-perfume-heart-notes-floral-bo.jpg",
      images: ["/rose-jasmine-flowers-perfume-heart-notes-floral-bo.jpg"],
      description: "An opulent jasmine fragrance that celebrates the queen of white flowers.",
      notesTop: ["Jasmine", "Orange Blossom", "Bergamot"],
      notesMiddle: ["Jasmine Absolute", "Tuberose", "Gardenia"],
      notesBase: ["White Musk", "Sandalwood", "Amber"],
      size: ["30ml", "50ml", "100ml"],
      inStock: true,
      isNew: false,
      isSale: false,
      badge: "Premium",
    },
    {
      name: "Alsa Fragrance - Lavender Fields",
      category: "women",
      price: 76.99,
      originalPrice: 96.99,
      salePrice: 76.99,
      salePercent: 21,
      rating: 4.5,
      reviews: 201,
      image: "/fresh-citrus-perfume-bottles-bright-clean.jpg",
      images: ["/fresh-citrus-perfume-bottles-bright-clean.jpg"],
      description: "A calming lavender fragrance that brings the serenity of Provence fields to your senses.",
      notesTop: ["Lavender", "Lemon", "Bergamot"],
      notesMiddle: ["Lavender Absolute", "Rosemary", "Thyme"],
      notesBase: ["Musk", "Cedarwood", "Amber"],
      size: ["30ml", "50ml", "100ml"],
      inStock: true,
      isNew: false,
      isSale: true,
      badge: "Sale",
    },
    {
      name: "Alsa Fragrance - Vanilla Dreams",
      category: "women",
      price: 85.99,
      rating: 4.6,
      reviews: 178,
      image: "/sandalwood-vanilla-amber-warm-ingredients-perfume-.jpg",
      images: ["/sandalwood-vanilla-amber-warm-ingredients-perfume-.jpg"],
      description: "A warm, comforting vanilla fragrance that wraps you in cozy, dreamy sweetness.",
      notesTop: ["Vanilla", "Caramel", "Almond"],
      notesMiddle: ["Vanilla Absolute", "Tonka Bean", "Honey"],
      notesBase: ["Amber", "Sandalwood", "Musk"],
      size: ["30ml", "50ml", "100ml"],
      inStock: true,
      isNew: true,
      isSale: false,
      badge: "New",
    },
    {
      name: "Alsa Fragrance - Citrus Burst",
      category: "women",
      price: 72.99,
      originalPrice: 92.99,
      salePrice: 72.99,
      salePercent: 22,
      rating: 4.4,
      reviews: 156,
      image: "/citrus-bergamot-lemon-fresh-ingredients-perfume-to.jpg",
      images: ["/citrus-bergamot-lemon-fresh-ingredients-perfume-to.jpg"],
      description: "A vibrant citrus fragrance that bursts with energy and freshness.",
      notesTop: ["Lemon", "Grapefruit", "Bergamot"],
      notesMiddle: ["Orange", "Mandarin", "Lime"],
      notesBase: ["White Musk", "Cedar", "Amber"],
      size: ["30ml", "50ml", "100ml"],
      inStock: true,
      isNew: false,
      isSale: true,
      badge: "Sale",
    },
  ],
  men: [
    {
      name: "Alsa Fragrance - Titanium Force",
      category: "men",
      price: 89.99,
      rating: 4.8,
      reviews: 167,
      image: "/powerful-titanium-cologne-bottle-with-alsa-fragran.jpg",
      images: ["/powerful-titanium-cologne-bottle-with-alsa-fragran.jpg"],
      description: "A powerful, metallic fragrance that embodies strength and modern masculinity.",
      notesTop: ["Grapefruit", "Black Pepper", "Ginger"],
      notesMiddle: ["Titanium Accord", "Cedar", "Vetiver"],
      notesBase: ["Leather", "Amber", "Musk"],
      size: ["50ml", "100ml"],
      inStock: true,
      isNew: true,
      isSale: false,
      badge: "New",
    },
    {
      name: "Alsa Fragrance - Platinum Elite",
      category: "men",
      price: 94.99,
      rating: 4.7,
      reviews: 189,
      image: "/platinum-silver-cologne-bottle-with-alsa-fragrance.jpg",
      images: ["/platinum-silver-cologne-bottle-with-alsa-fragrance.jpg"],
      description: "An elite fragrance with platinum sophistication and refined elegance.",
      notesTop: ["Bergamot", "Lemon", "Mint"],
      notesMiddle: ["Platinum Accord", "Lavender", "Geranium"],
      notesBase: ["Sandalwood", "Amber", "Musk"],
      size: ["50ml", "100ml"],
      inStock: true,
      isNew: false,
      isSale: false,
      badge: "Premium",
    },
    {
      name: "Alsa Fragrance - Sapphire Blue",
      category: "men",
      price: 87.99,
      originalPrice: 107.99,
      salePrice: 87.99,
      salePercent: 19,
      rating: 4.6,
      reviews: 145,
      image: "/luxury-blue-sapphire-perfume-bottle-with-alsa-frag.jpg",
      images: ["/luxury-blue-sapphire-perfume-bottle-with-alsa-frag.jpg"],
      description: "A deep blue aquatic fragrance that captures the essence of the ocean's depth.",
      notesTop: ["Sea Salt", "Bergamot", "Aquatic Notes"],
      notesMiddle: ["Marine Accord", "Sage", "Geranium"],
      notesBase: ["Driftwood", "Ambergris", "White Musk"],
      size: ["50ml", "100ml"],
      inStock: true,
      isNew: false,
      isSale: true,
      badge: "Sale",
    },
    {
      name: "Alsa Fragrance - Ruby Passion",
      category: "men",
      price: 91.99,
      rating: 4.8,
      reviews: 178,
      image: "/red-ruby-perfume-bottle-with-alsa-fragrance-logo-e.jpg",
      images: ["/red-ruby-perfume-bottle-with-alsa-fragrance-logo-e.jpg"],
      description: "A passionate red fragrance with fiery intensity and bold character.",
      notesTop: ["Red Pepper", "Ginger", "Cardamom"],
      notesMiddle: ["Cinnamon", "Clove", "Rose"],
      notesBase: ["Leather", "Amber", "Musk"],
      size: ["50ml", "100ml"],
      inStock: true,
      isNew: true,
      isSale: false,
      badge: "New",
    },
    {
      name: "Alsa Fragrance - Midnight Warrior",
      category: "men",
      price: 93.99,
      rating: 4.9,
      reviews: 201,
      image: "/dark-storm-cologne-bottle-with-lightning-alsa-frag.jpg",
      images: ["/dark-storm-cologne-bottle-with-lightning-alsa-frag.jpg"],
      description: "A dark, intense fragrance for the warrior who commands respect and power.",
      notesTop: ["Black Pepper", "Grapefruit", "Ozone"],
      notesMiddle: ["Storm Accord", "Cypress", "Juniper"],
      notesBase: ["Dark Woods", "Leather", "Smoky Amber"],
      size: ["50ml", "100ml"],
      inStock: true,
      isNew: false,
      isSale: false,
      badge: "Intense",
    },
    {
      name: "Alsa Fragrance - Forest Explorer",
      category: "men",
      price: 86.99,
      rating: 4.7,
      reviews: 156,
      image: "/forest-green-cologne-bottle-with-tree-alsa-fragran.jpg",
      images: ["/forest-green-cologne-bottle-with-tree-alsa-fragran.jpg"],
      description: "A rugged woodland fragrance for the adventurous explorer.",
      notesTop: ["Pine", "Eucalyptus", "Lemon"],
      notesMiddle: ["Cedar", "Fir", "Sage"],
      notesBase: ["Oakmoss", "Patchouli", "Amber"],
      size: ["50ml", "100ml"],
      inStock: true,
      isNew: true,
      isSale: false,
      badge: "New",
    },
    {
      name: "Alsa Fragrance - Desert Nomad",
      category: "men",
      price: 88.99,
      originalPrice: 108.99,
      salePrice: 88.99,
      salePercent: 18,
      rating: 4.6,
      reviews: 167,
      image: "/bronze-desert-cologne-bottle-with-gold-alsa-fragra.jpg",
      images: ["/bronze-desert-cologne-bottle-with-gold-alsa-fragra.jpg"],
      description: "An exotic desert fragrance inspired by the mystique of ancient trade routes.",
      notesTop: ["Cardamom", "Orange", "Cinnamon"],
      notesMiddle: ["Frankincense", "Myrrh", "Rose"],
      notesBase: ["Oud", "Sandalwood", "Vanilla"],
      size: ["50ml", "100ml"],
      inStock: true,
      isNew: false,
      isSale: true,
      badge: "Sale",
    },
    {
      name: "Alsa Fragrance - Urban Elite",
      category: "men",
      price: 90.99,
      rating: 4.8,
      reviews: 189,
      image: "/modern-black-cologne-bottle-with-silver-alsa-fragr.jpg",
      images: ["/modern-black-cologne-bottle-with-silver-alsa-fragr.jpg"],
      description: "A modern urban fragrance for the contemporary gentleman.",
      notesTop: ["Lemon", "Grapefruit", "Mint"],
      notesMiddle: ["Lavender", "Geranium", "Cardamom"],
      notesBase: ["Cedarwood", "Vetiver", "Ambergris"],
      size: ["50ml", "100ml"],
      inStock: true,
      isNew: false,
      isSale: false,
      badge: null,
    },
    {
      name: "Alsa Fragrance - Steel Edge",
      category: "men",
      price: 92.99,
      rating: 4.7,
      reviews: 145,
      image: "/metallic-steel-cologne-bottle-with-fire-alsa-fragr.jpg",
      images: ["/metallic-steel-cologne-bottle-with-fire-alsa-fragr.jpg"],
      description: "A bold industrial fragrance combining metallic coolness with fiery passion.",
      notesTop: ["Metallic Notes", "Red Pepper", "Ginger"],
      notesMiddle: ["Steel Accord", "Black Tea", "Cardamom"],
      notesBase: ["Smoky Woods", "Leather", "Burnt Amber"],
      size: ["50ml", "100ml"],
      inStock: true,
      isNew: true,
      isSale: false,
      badge: "New",
    },
    {
      name: "Alsa Fragrance - Royal Crown",
      category: "men",
      price: 96.99,
      rating: 4.9,
      reviews: 234,
      image: "/royal-gold-cologne-bottle-with-crown-alsa-fragranc.jpg",
      images: ["/royal-gold-cologne-bottle-with-crown-alsa-fragranc.jpg"],
      description: "A regal masculine fragrance fit for royalty, exuding power and sophistication.",
      notesTop: ["Royal Saffron", "Bergamot", "Pink Pepper"],
      notesMiddle: ["Royal Rose", "Oud", "Cinnamon"],
      notesBase: ["Royal Amber", "Sandalwood", "Musk"],
      size: ["50ml", "100ml"],
      inStock: true,
      isNew: false,
      isSale: false,
      badge: "Royal",
    },
  ],
  attars: [
    {
      name: "Alsa Fragrance - Premium Oud",
      category: "attars",
      price: 149.99,
      rating: 4.9,
      reviews: 89,
      image: "/royal-oud-perfume-bottles-luxury-gold.jpg",
      images: ["/royal-oud-perfume-bottles-luxury-gold.jpg"],
      description: "Premium oud attar crafted from the finest agarwood, embodying luxury and tradition.",
      notesTop: ["Saffron", "Rose"],
      notesMiddle: ["Oud", "Amber"],
      notesBase: ["Musk", "Sandalwood", "Patchouli"],
      size: ["6ml", "12ml"],
      inStock: true,
      isNew: true,
      isSale: false,
      badge: "Premium",
    },
    {
      name: "Alsa Fragrance - Pure Rose",
      category: "attars",
      price: 129.99,
      rating: 4.8,
      reviews: 134,
      image: "/rose-jasmine-flowers-perfume-heart-notes-floral-bo.jpg",
      images: ["/rose-jasmine-flowers-perfume-heart-notes-floral-bo.jpg"],
      description: "A divine rose attar that captures the pure essence of Damascus roses.",
      notesTop: ["Bulgarian Rose", "Turkish Rose"],
      notesMiddle: ["Damask Rose", "Rose Otto"],
      notesBase: ["Rose Absolute", "Sandalwood", "Musk"],
      size: ["6ml", "12ml"],
      inStock: true,
      isNew: false,
      isSale: false,
      badge: "Pure",
    },
    {
      name: "Alsa Fragrance - Sacred Sandalwood",
      category: "attars",
      price: 119.99,
      rating: 4.7,
      reviews: 156,
      image: "/sandalwood-vanilla-amber-warm-ingredients-perfume-.jpg",
      images: ["/sandalwood-vanilla-amber-warm-ingredients-perfume-.jpg"],
      description: "A sacred sandalwood attar that brings peace and spiritual harmony.",
      notesTop: ["Mysore Sandalwood"],
      notesMiddle: ["Australian Sandalwood", "Cardamom"],
      notesBase: ["Sandalwood Absolute", "White Musk", "Amber"],
      size: ["6ml", "12ml"],
      inStock: true,
      isNew: false,
      isSale: false,
      badge: "Sacred",
    },
    {
      name: "Alsa Fragrance - Amber Nights",
      category: "attars",
      price: 124.99,
      rating: 4.6,
      reviews: 178,
      image: "/golden-amber-perfume-bottle-with-alsa-fragrance-lo.jpg",
      images: ["/golden-amber-perfume-bottle-with-alsa-fragrance-lo.jpg"],
      description: "A warm amber attar that evokes the mystery and allure of Arabian nights.",
      notesTop: ["Saffron", "Cardamom"],
      notesMiddle: ["Amber", "Frankincense"],
      notesBase: ["Amber Absolute", "Oud", "Musk"],
      size: ["6ml", "12ml"],
      inStock: true,
      isNew: true,
      isSale: false,
      badge: "New",
    },
    {
      name: "Alsa Fragrance - White Musk",
      category: "attars",
      price: 109.99,
      originalPrice: 139.99,
      salePrice: 109.99,
      salePercent: 21,
      rating: 4.5,
      reviews: 201,
      image: "/crystal-clear-perfume-bottle-with-silver-alsa-frag.jpg",
      images: ["/crystal-clear-perfume-bottle-with-silver-alsa-frag.jpg"],
      description: "A pure white musk attar that embodies cleanliness and spiritual purity.",
      notesTop: ["White Musk"],
      notesMiddle: ["Clean Musk", "Soft Florals"],
      notesBase: ["Musk Absolute", "White Amber", "Soft Woods"],
      size: ["6ml", "12ml"],
      inStock: true,
      isNew: false,
      isSale: true,
      badge: "Sale",
    },
    {
      name: "Alsa Fragrance - Black Oudh Supreme",
      category: "attars",
      price: 179.99,
      rating: 4.9,
      reviews: 67,
      image: "/royal-oud-perfume-bottles-luxury-gold.jpg",
      images: ["/royal-oud-perfume-bottles-luxury-gold.jpg"],
      description: "The ultimate oud experience - rare black oud from the heart of Cambodia.",
      notesTop: ["Cambodian Oud"],
      notesMiddle: ["Black Oud", "Rose"],
      notesBase: ["Oud Absolute", "Amber", "Musk"],
      size: ["3ml", "6ml", "12ml"],
      inStock: true,
      isNew: false,
      isSale: false,
      badge: "Supreme",
    },
    {
      name: "Alsa Fragrance - Golden Saffron",
      category: "attars",
      price: 139.99,
      rating: 4.8,
      reviews: 123,
      image: "/golden-amber-perfume-bottle-with-alsa-fragrance-lo.jpg",
      images: ["/golden-amber-perfume-bottle-with-alsa-fragrance-lo.jpg"],
      description: "A precious saffron attar made from the finest Kashmir saffron.",
      notesTop: ["Kashmir Saffron", "Rose"],
      notesMiddle: ["Saffron Absolute", "Cardamom"],
      notesBase: ["Golden Amber", "Musk", "Sandalwood"],
      size: ["6ml", "12ml"],
      inStock: true,
      isNew: true,
      isSale: false,
      badge: "New",
    },
    {
      name: "Alsa Fragrance - Jasmine Nights",
      category: "attars",
      price: 134.99,
      rating: 4.7,
      reviews: 167,
      image: "/rose-jasmine-flowers-perfume-heart-notes-floral-bo.jpg",
      images: ["/rose-jasmine-flowers-perfume-heart-notes-floral-bo.jpg"],
      description: "An intoxicating jasmine attar that blooms in the darkness of night.",
      notesTop: ["Night Jasmine", "Sambac Jasmine"],
      notesMiddle: ["Jasmine Absolute", "White Flowers"],
      notesBase: ["Jasmine Essence", "White Musk", "Soft Woods"],
      size: ["6ml", "12ml"],
      inStock: true,
      isNew: false,
      isSale: false,
      badge: "Intoxicating",
    },
    {
      name: "Alsa Fragrance - Eternal Love",
      category: "attars",
      price: 159.99,
      rating: 4.9,
      reviews: 56,
      image: "/pink-rose-gold-perfume-bottle-with-alsa-fragrance-.jpg",
      images: ["/pink-rose-gold-perfume-bottle-with-alsa-fragrance-.jpg"],
      description: "A romantic attar that captures the essence of eternal, undying love.",
      notesTop: ["Love Accord", "Rose", "Saffron"],
      notesMiddle: ["Heart Flowers", "Romantic Spices", "Amber"],
      notesBase: ["Eternal Musk", "Love Potion", "Sacred Woods"],
      size: ["6ml", "12ml"],
      inStock: true,
      isNew: true,
      isSale: false,
      badge: "Romantic",
    },
    {
      name: "Alsa Fragrance - Mystic Oud",
      category: "attars",
      price: 169.99,
      originalPrice: 199.99,
      salePrice: 169.99,
      salePercent: 15,
      rating: 4.8,
      reviews: 98,
      image: "/royal-oud-perfume-bottles-luxury-gold.jpg",
      images: ["/royal-oud-perfume-bottles-luxury-gold.jpg"],
      description: "A mystical oud attar with deep, complex notes that transport you to ancient times.",
      notesTop: ["Saffron", "Rose", "Cardamom"],
      notesMiddle: ["Mystic Oud", "Amber", "Frankincense"],
      notesBase: ["Oud Absolute", "Musk", "Sandalwood"],
      size: ["6ml", "12ml"],
      inStock: true,
      isNew: false,
      isSale: true,
      badge: "Sale",
    },
  ],
  testers: [
    {
      name: "Alsa Fragrance - Blossom Dreams Tester",
      category: "testers",
      price: 29.99,
      originalPrice: 39.99,
      salePrice: 29.99,
      salePercent: 25,
      rating: 4.7,
      reviews: 89,
      image: "/pink-rose-gold-perfume-bottle-with-alsa-fragrance-.jpg",
      images: ["/pink-rose-gold-perfume-bottle-with-alsa-fragrance-.jpg"],
      description: "Tester version of our bestselling Blossom Dreams fragrance.",
      notesTop: ["Peach", "Apricot", "Bergamot"],
      notesMiddle: ["Rose", "Jasmine", "Lily"],
      notesBase: ["Musk", "Vanilla", "Sandalwood"],
      size: ["30ml"],
      inStock: true,
      isNew: false,
      isSale: true,
      badge: "Tester",
    },
    {
      name: "Alsa Fragrance - Titanium Force Tester",
      category: "testers",
      price: 34.99,
      originalPrice: 44.99,
      salePrice: 34.99,
      salePercent: 22,
      rating: 4.8,
      reviews: 123,
      image: "/powerful-titanium-cologne-bottle-with-alsa-fragran.jpg",
      images: ["/powerful-titanium-cologne-bottle-with-alsa-fragran.jpg"],
      description: "Tester version of our powerful Titanium Force masculine fragrance.",
      notesTop: ["Grapefruit", "Black Pepper", "Ginger"],
      notesMiddle: ["Titanium Accord", "Cedar", "Vetiver"],
      notesBase: ["Leather", "Amber", "Musk"],
      size: ["30ml"],
      inStock: true,
      isNew: false,
      isSale: true,
      badge: "Tester",
    },
    {
      name: "Alsa Fragrance - Premium Oud Tester",
      category: "testers",
      price: 49.99,
      originalPrice: 59.99,
      salePrice: 49.99,
      salePercent: 17,
      rating: 4.9,
      reviews: 67,
      image: "/royal-oud-perfume-bottles-luxury-gold.jpg",
      images: ["/royal-oud-perfume-bottles-luxury-gold.jpg"],
      description: "Tester version of our premium Premium Oud attar.",
      notesTop: ["Saffron", "Rose"],
      notesMiddle: ["Oud", "Amber"],
      notesBase: ["Musk", "Sandalwood", "Patchouli"],
      size: ["6ml"],
      inStock: true,
      isNew: false,
      isSale: true,
      badge: "Tester",
    },
    {
      name: "Alsa Fragrance - Pearl Essence Tester",
      category: "testers",
      price: 32.99,
      originalPrice: 42.99,
      salePrice: 32.99,
      salePercent: 23,
      rating: 4.7,
      reviews: 78,
      image: "/crystal-clear-perfume-bottle-with-silver-alsa-frag.jpg",
      images: ["/crystal-clear-perfume-bottle-with-silver-alsa-frag.jpg"],
      description: "Tester version of our limited edition Pearl Essence fragrance.",
      notesTop: ["Pear", "Freesia", "Water Lily"],
      notesMiddle: ["Magnolia", "Lotus", "White Tea"],
      notesBase: ["Crystal Musk", "Blonde Woods", "Soft Amber"],
      size: ["30ml"],
      inStock: true,
      isNew: false,
      isSale: true,
      badge: "Tester",
    },
    {
      name: "Alsa Fragrance - Sapphire Blue Tester",
      category: "testers",
      price: 31.99,
      originalPrice: 41.99,
      salePrice: 31.99,
      salePercent: 24,
      rating: 4.6,
      reviews: 94,
      image: "/luxury-blue-sapphire-perfume-bottle-with-alsa-frag.jpg",
      images: ["/luxury-blue-sapphire-perfume-bottle-with-alsa-frag.jpg"],
      description: "Tester version of our refreshing Sapphire Blue masculine fragrance.",
      notesTop: ["Sea Salt", "Bergamot", "Aquatic Notes"],
      notesMiddle: ["Marine Accord", "Sage", "Geranium"],
      notesBase: ["Driftwood", "Ambergris", "White Musk"],
      size: ["30ml"],
      inStock: true,
      isNew: false,
      isSale: true,
      badge: "Tester",
    },
    {
      name: "Alsa Fragrance - Velvet Rose Tester",
      category: "testers",
      price: 33.99,
      originalPrice: 43.99,
      salePrice: 33.99,
      salePercent: 23,
      rating: 4.8,
      reviews: 112,
      image: "/elegant-black-perfume-bottle-with-gold-alsa-fragra.jpg",
      images: ["/elegant-black-perfume-bottle-with-gold-alsa-fragra.jpg"],
      description: "Tester version of our luxurious Velvet Rose fragrance.",
      notesTop: ["Black Currant", "Pink Pepper", "Bergamot"],
      notesMiddle: ["Damask Rose", "Peony", "Violet"],
      notesBase: ["Patchouli", "Amber", "Musk"],
      size: ["30ml"],
      inStock: true,
      isNew: false,
      isSale: true,
      badge: "Tester",
    },
    {
      name: "Alsa Fragrance - Desert Nomad Tester",
      category: "testers",
      price: 32.99,
      originalPrice: 42.99,
      salePrice: 32.99,
      salePercent: 24,
      rating: 4.6,
      reviews: 89,
      image: "/bronze-desert-cologne-bottle-with-gold-alsa-fragra.jpg",
      images: ["/bronze-desert-cologne-bottle-with-gold-alsa-fragra.jpg"],
      description: "Tester version of our exotic Desert Nomad masculine fragrance.",
      notesTop: ["Cardamom", "Orange", "Cinnamon"],
      notesMiddle: ["Frankincense", "Myrrh", "Rose"],
      notesBase: ["Oud", "Sandalwood", "Vanilla"],
      size: ["30ml"],
      inStock: true,
      isNew: false,
      isSale: true,
      badge: "Tester",
    },
    {
      name: "Alsa Fragrance - Mystic Garden Tester",
      category: "testers",
      price: 34.99,
      originalPrice: 44.99,
      salePrice: 34.99,
      salePercent: 22,
      rating: 4.9,
      reviews: 67,
      image: "/emerald-green-perfume-bottle-with-gold-alsa-fragra.jpg",
      images: ["/emerald-green-perfume-bottle-with-gold-alsa-fragra.jpg"],
      description: "Tester version of our enchanting Mystic Garden fragrance.",
      notesTop: ["Green Mandarin", "Basil", "Mint"],
      notesMiddle: ["Green Tea", "Bamboo", "Lily of the Valley"],
      notesBase: ["Vetiver", "White Cedar", "Green Musk"],
      size: ["30ml"],
      inStock: true,
      isNew: false,
      isSale: true,
      badge: "Tester",
    },
    {
      name: "Alsa Fragrance - Midnight Warrior Tester",
      category: "testers",
      price: 35.99,
      originalPrice: 45.99,
      salePrice: 35.99,
      salePercent: 22,
      rating: 4.8,
      reviews: 98,
      image: "/dark-storm-cologne-bottle-with-lightning-alsa-frag.jpg",
      images: ["/dark-storm-cologne-bottle-with-lightning-alsa-frag.jpg"],
      description: "Tester version of our intense Midnight Warrior masculine fragrance.",
      notesTop: ["Black Pepper", "Grapefruit", "Ozone"],
      notesMiddle: ["Storm Accord", "Cypress", "Juniper"],
      notesBase: ["Dark Woods", "Leather", "Smoky Amber"],
      size: ["30ml"],
      inStock: true,
      isNew: false,
      isSale: true,
      badge: "Tester",
    },
    {
      name: "Alsa Fragrance - Royal Crown Tester",
      category: "testers",
      price: 36.99,
      originalPrice: 46.99,
      salePrice: 36.99,
      salePercent: 21,
      rating: 4.9,
      reviews: 145,
      image: "/royal-gold-cologne-bottle-with-crown-alsa-fragranc.jpg",
      images: ["/royal-gold-cologne-bottle-with-crown-alsa-fragranc.jpg"],
      description: "Tester version of our regal Royal Crown masculine fragrance.",
      notesTop: ["Royal Saffron", "Bergamot", "Pink Pepper"],
      notesMiddle: ["Royal Rose", "Oud", "Cinnamon"],
      notesBase: ["Royal Amber", "Sandalwood", "Musk"],
      size: ["30ml"],
      inStock: true,
      isNew: false,
      isSale: true,
      badge: "Tester",
    },
  ],
}

async function main() {
  console.log('Starting to add 10 products per category to MongoDB Atlas...\n')

  // Connect to MongoDB
  await connectDB()
  console.log('✅ Connected to MongoDB Atlas\n')

  let totalImported = 0
  let totalFailed = 0

  // Add products for each category
  for (const [category, products] of Object.entries(newProducts)) {
    console.log(`\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`)
    console.log(`Adding ${products.length} products for category: ${category.toUpperCase()}`)
    console.log(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`)

    let categoryImported = 0
    let categoryFailed = 0

    for (const product of products) {
      try {
        await Product.create(product)
        categoryImported++
        totalImported++
        console.log(`[${categoryImported}/${products.length}] ✅ Imported: ${product.name}`)
      } catch (error: any) {
        categoryFailed++
        totalFailed++
        console.error(`❌ Error importing ${product.name}:`, error.message)
      }
    }

    console.log(`\nCategory ${category.toUpperCase()} Summary:`)
    console.log(`  - Successfully imported: ${categoryImported}`)
    console.log(`  - Failed: ${categoryFailed}`)
  }

  const totalInDb = await Product.countDocuments()
  const byCategory = {
    women: await Product.countDocuments({ category: 'women' }),
    men: await Product.countDocuments({ category: 'men' }),
    attars: await Product.countDocuments({ category: 'attars' }),
    testers: await Product.countDocuments({ category: 'testers' }),
  }

  console.log(`\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`)
  console.log(`✨ Product import completed!`)
  console.log(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`)
  console.log(`Total Summary:`)
  console.log(`  - Successfully imported: ${totalImported}`)
  console.log(`  - Failed: ${totalFailed}`)
  console.log(`  - Total products in database: ${totalInDb}`)
  console.log(`\nProducts by Category:`)
  console.log(`  - Women: ${byCategory.women}`)
  console.log(`  - Men: ${byCategory.men}`)
  console.log(`  - Attars: ${byCategory.attars}`)
  console.log(`  - Testers: ${byCategory.testers}`)
  console.log(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n`)
}

main()
  .catch((e) => {
    console.error('Fatal error:', e)
    process.exit(1)
  })
  .finally(() => {
    process.exit(0)
  })



